const test=require('node:test');const assert=require('node:assert/strict');const C=require('../src/email-concierge/core');
const mk=(provider=C.ProviderType.GMAIL,id='a1',person='p1')=>C.emailAccount({email_account_id:id,person_id:person,provider_type:provider,email_address:`${id}@example.test`,auth_method:provider===C.ProviderType.GMAIL||provider===C.ProviderType.MICROSOFT?C.AuthMethod.OAUTH:C.AuthMethod.EMAIL_PROGRAM_PASSWORD,credential_ref:'server-ref'});
const raw=(o={})=>({id:o.id||'m1',subject:o.subject||'Hallo',text_body:o.text_body||'Text',attachments:o.attachments||[],links:o.links||[],read_state:o.read_state||'UNREAD',importance:o.importance||'NORMAL',thread_id:o.thread_id||'t1'});
const providers=[C.ProviderType.GMAIL,C.ProviderType.GMX,C.ProviderType.T_ONLINE,C.ProviderType.MICROSOFT,C.ProviderType.GENERIC_IMAP];
providers.forEach((p,i)=>test(`${i+1} ${p} account`,()=>assert.equal(mk(p).provider_type,p)));
test('6 multiple accounts per person',()=>assert.equal(new Set([mk(C.ProviderType.GMX,'a','p'),mk(C.ProviderType.GMAIL,'b','p')].map(x=>x.person_id)).size,1));
test('7 wrong person id',()=>assert.throws(()=>C.authorize(mk(),{person_id:'x'}),/PERSON_MISMATCH/));
test('8 family without permission',()=>assert.throws(()=>C.authorize(mk(),{person_id:'p1',actor_person_id:'family',scopes:[]}),/AUTHORIZATION_REQUIRED/));
test('9 family with email.read',()=>assert.equal(C.authorize(mk(),{person_id:'p1',actor_person_id:'family',scopes:['email.read']}),true));
test('10 header first',()=>{const m=C.normalizeMessage(mk(),raw());assert.equal(m.text_body,null)});
test('11 content on demand',()=>assert.equal(C.normalizeMessage(mk(),raw(),{includeContent:true}).text_body,'Text'));
test('12 attachment on demand',()=>{const a=[{id:'x',name:'a.pdf',size:2,data:'secret'}];assert.equal(C.normalizeMessage(mk(),raw({attachments:a})).attachments[0].loaded,false)});
test('13 incremental sync cursor',async()=>{const f=new C.FixtureEmailConnector([raw()]);const r=await f.list_messages({cursor:'old'});assert.equal(r.cursor,'c1');assert.equal(f.calls[0][1],'old')});
test('14 provider unavailable',async()=>await assert.rejects(()=>new C.FixtureEmailConnector([],{unavailable:true}).list_messages(),C.ProviderUnavailable));
test('15 rate limit',async()=>await assert.rejects(()=>new C.FixtureEmailConnector([],{rateLimited:true}).list_messages(),C.RateLimited));
test('16 important',()=>assert.equal(C.classify(raw({subject:'Wichtig'})).classification,C.Classification.IMPORTANT));
test('17 invoice',()=>assert.equal(C.classify(raw({subject:'Rechnung fällig'})).classification,C.Classification.INVOICE));
test('18 contract',()=>assert.equal(C.classify(raw({subject:'Vertragsänderung'})).classification,C.Classification.CONTRACT));
test('19 appointment',()=>assert.equal(C.classify(raw({subject:'Termin'})).classification,C.Classification.APPOINTMENT));
test('20 personal',()=>assert.equal(C.classify(raw({subject:'Liebe Familie'})).classification,C.Classification.PERSONAL));
test('21 newsletter not spam',()=>assert.equal(C.classify(raw({subject:'Newsletter'})).classification,C.Classification.NEWSLETTER));
test('22 fraud suspected',()=>assert.equal(C.classify(raw({subject:'Bitte Zugangsdaten bestätigen'})).classification,C.Classification.FRAUD_SUSPECTED));
test('23 document hook',()=>{const m={attachments:[{name:'r.pdf'}]};assert.equal(C.documentHook(m,{analyze:a=>a.name})[0],'r.pdf')});
test('24 fraud hook',()=>assert.equal(C.fraudHook({links:['x']},[],{assess:x=>x.links.length}),1));
test('25 memory proves no authenticity',()=>assert.equal(C.memoryContext({known_provider:'x'}).proves_authenticity,false));
test('26 daily digest',()=>assert.equal(C.digest([C.normalizeMessage(mk(),raw(),{includeContent:true})]).count,1));
test('27 important only digest',()=>{const a=C.normalizeMessage(mk(),raw({subject:'Rechnung'}),{includeContent:true});const b=C.normalizeMessage(mk(),raw({id:'2'}),{includeContent:true});assert.equal(C.digest([a,b],'important_only_digest').count,1)});
test('28 no automatic delivery',()=>assert.equal(C.digest([]).automatic_delivery,false));
test('29 reply prepare',()=>assert.deepEqual(C.prepareAction('reply.prepare',{}).phase,'PREPARE'));
test('30 reply send blocked',()=>assert.throws(()=>new C.EmailProviderConnector().send_message(),C.ExecutionNotAllowed));
test('31 delete blocked',()=>assert.throws(()=>new C.EmailProviderConnector().delete_message(),C.ExecutionNotAllowed));
test('32 move blocked',()=>assert.throws(()=>new C.EmailProviderConnector().move_message(),C.ExecutionNotAllowed));
test('33 trash not permanent',()=>assert.equal(C.safeDeletePlan('m').permanent_delete,false));
test('34 no trash empty',()=>assert.equal(C.safeDeletePlan('m').empty_trash,false));
test('35 action approval hook',()=>assert.equal(C.prepareAction('archive',{}).approval_required,true));
test('36 credentials never in model',()=>assert.throws(()=>C.emailAccount({provider_type:C.ProviderType.GMX,password:'x'}),/forbidden/));
test('37 no secrets in audit',()=>assert.equal(C.audit({secret:'x'}).secret,'[REDACTED]'));
test('38 provider capabilities',()=>{assert.equal(C.CAPS.GMAIL.supports_oauth,true);assert.equal(C.CAPS.GMX.supports_oauth,false)});
test('39 providers normalize equally',()=>{const a=C.normalizeMessage(mk(C.ProviderType.GMAIL,'g'),raw());const b=C.normalizeMessage(mk(C.ProviderType.GMX,'x'),raw());assert.deepEqual(Object.keys(a),Object.keys(b))});
test('40 fixture data only',()=>{const f=new C.FixtureEmailConnector([raw({subject:'fixture'})]);assert.equal(f.messages[0].subject,'fixture')});