import test from 'node:test';import assert from 'node:assert/strict';
import {authorizeFamilyAction,createInvite,decideInvite,activateInvite,revokePermission,toMemoryAuthorizationContext,Sensitivity} from '../src/core.js';
const now=new Date('2026-08-26T00:00:00Z');
const base={permission_id:'p1',grantor_person_id:'mother',grantee_person_id:'anna',customer_account_id:'acct',permission_type:'reminder.create',scope:'senior',status:'active',granted_at:'2026-08-25T00:00:00Z',expires_at:'2026-09-01T00:00:00Z',revoked_at:null,source:'family_invite',metadata:{max_sensitivity:Sensitivity.PRIVATE}};
const req=(scope,permissions=[base],extra={})=>authorizeFamilyAction({actor_person_id:'anna',subject_person_id:'mother',customer_account_id:'acct',requested_scope:scope,permissions,now,...extra});
test('relationship without permission DENY',()=>assert.equal(req('reminder.create',[]).allowed,false));
test('active matching permission ALLOW',()=>assert.equal(req('reminder.create').allowed,true));
test('wrong scope DENY',()=>assert.equal(req('reminder.read').allowed,false));
test('revoked DENY',()=>assert.equal(req('reminder.create',[{...base,status:'revoked'}]).allowed,false));
test('expired DENY',()=>assert.equal(req('reminder.create',[{...base,expires_at:'2026-08-25T00:00:00Z'}]).allowed,false));
test('pending DENY',()=>assert.equal(req('reminder.create',[{...base,status:'pending'}]).allowed,false));
test('rejected DENY',()=>assert.equal(req('reminder.create',[{...base,status:'rejected'}]).allowed,false));
test('wrong actor DENY',()=>assert.equal(authorizeFamilyAction({actor_person_id:'max',subject_person_id:'mother',customer_account_id:'acct',requested_scope:'reminder.create',permissions:[base],now}).allowed,false));
test('wrong subject DENY',()=>assert.equal(authorizeFamilyAction({actor_person_id:'anna',subject_person_id:'father',customer_account_id:'acct',requested_scope:'reminder.create',permissions:[base],now}).allowed,false));
test('reminder read != create',()=>assert.equal(req('reminder.read').allowed,false));
test('reminder create != delete',()=>assert.equal(req('reminder.delete').allowed,false));
for(const [a,b] of [['mobility.information','mobility.prepare'],['mobility.prepare','mobility.approve'],['mobility.approve','mobility.execute']])test(`${a} != ${b}`,()=>assert.equal(req(b,[{...base,permission_type:a}]).allowed,false));
test('memory without memory.read DENY',()=>assert.equal(req('memory.read').allowed,false));
test('allowed memory scope creates context',()=>{const p={...base,permission_type:'memory.read',metadata:{max_sensitivity:Sensitivity.SENSITIVE}};const a=req('memory.read',[p]);assert.equal(toMemoryAuthorizationContext(a,{categories:['devices']}).authorized,true)});
test('client authorization not trusted',()=>assert.equal(req('reminder.create',[base],{context:{client_authorized:true}}).allowed,false));
test('sensitivity boundary',()=>assert.equal(req('reminder.create',[base],{context:{sensitivity:Sensitivity.RESTRICTED}}).allowed,false));
test('invite consent activates permissions',()=>{const i=createInvite({invite_id:'i1',grantor_person_id:'mother',grantee_person_id:'anna',customer_account_id:'acct',requested_scopes:['reminder.create'],expires_at:'2026-08-27T00:00:00Z'},now);const accepted=decideInvite(i,{subject_person_id:'mother',decision:'consent'},now);assert.equal(activateInvite(accepted,now)[0].status,'active')});
test('invite reject',()=>{const i=createInvite({invite_id:'i2',grantor_person_id:'mother',grantee_person_id:'anna',customer_account_id:'acct',requested_scopes:['support.request'],expires_at:'2026-08-27T00:00:00Z'},now);assert.equal(decideInvite(i,{subject_person_id:'mother',decision:'reject'},now).status,'rejected')});
test('invite expiry',()=>{const i=createInvite({invite_id:'i3',grantor_person_id:'mother',grantee_person_id:'anna',customer_account_id:'acct',requested_scopes:['support.request'],expires_at:'2026-08-26T01:00:00Z'},now);assert.equal(decideInvite(i,{subject_person_id:'mother',decision:'consent'},new Date('2026-08-27T00:00:00Z')).status,'expired')});
test('wrong invite subject rejected',()=>{const i=createInvite({invite_id:'i4',grantor_person_id:'mother',grantee_person_id:'anna',customer_account_id:'acct',requested_scopes:['support.request'],expires_at:'2026-08-27T00:00:00Z'},now);assert.throws(()=>decideInvite(i,{subject_person_id:'father',decision:'consent'},now))});
test('revoke immediately denies',()=>assert.equal(req('reminder.create',[revokePermission(base,now)]).allowed,false));
test('fixtures contain no real customer data',()=>assert.ok(['mother','anna','acct'].every(x=>JSON.stringify(base).includes(x))));
