from pathlib import Path


def must_replace(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected exactly one match in {path}, got {count}: {old[:140]}")
    p.write_text(text.replace(old, new, 1))


konto = "konto.html"
js = "assets/email-account-integration.js"
css = "assets/email-account-integration.css"
test = "tests/email-account-integration.test.mjs"

must_replace(konto,'<link rel="stylesheet" href="assets/email-account-integration.css?v=1" />','<link rel="stylesheet" href="assets/email-account-integration.css?v=2" />')
must_replace(konto,'<script src="assets/email-account-integration.js?v=2"></script>','<script src="assets/email-account-integration.js?v=3"></script>')
old_block='<div><div class="eyebrow">Gewünschte Funktionen</div><div class="email-capabilities"><label class="email-capability"><input type="checkbox" value="EMAIL_READ" data-email-capability checked disabled /><span>E-Mails lesen</span></label><label class="email-capability"><input type="checkbox" value="EMAIL_SEARCH" data-email-capability checked disabled /><span>E-Mails suchen</span></label><label class="email-capability"><input type="checkbox" value="EMAIL_ATTACHMENTS" data-email-capability checked disabled /><span>Anhänge berücksichtigen</span></label><label class="email-capability"><input type="checkbox" value="EMAIL_DRAFT" data-email-capability checked disabled /><span>Entwürfe vorbereiten</span></label><label class="email-capability"><input type="checkbox" value="EMAIL_SEND" data-email-capability checked disabled /><span>Nach Freigabe senden</span></label></div></div>'
new_block='<div><div class="eyebrow">Endkunden-Steuerung</div><div class="email-capabilities" aria-label="E-Mail-Funktionen"><label class="email-capability"><input type="checkbox" value="EMAIL_READ" data-email-capability checked disabled /><span><strong>E-Mails lesen</strong><small>Inhalte öffnen und zusammenfassen</small></span></label><label class="email-capability"><input type="checkbox" value="EMAIL_SEARCH" data-email-capability checked disabled /><span><strong>E-Mails suchen</strong><small>Gezielt im verbundenen Postfach suchen</small></span></label><label class="email-capability"><input type="checkbox" value="EMAIL_ATTACHMENTS" data-email-capability checked disabled /><span><strong>Anhänge berücksichtigen</strong><small>Sichere Anhänge in Aufgaben einbeziehen</small></span></label><label class="email-capability"><input type="checkbox" value="EMAIL_DRAFT" data-email-capability checked disabled /><span><strong>Entwürfe vorbereiten</strong><small>Antworten vorbereiten, noch nicht senden</small></span></label><label class="email-capability"><input type="checkbox" value="EMAIL_MAILBOX" data-email-capability checked disabled /><span><strong>Postfach verwalten</strong><small>Als gelesen markieren, archivieren oder in den Papierkorb</small></span></label><label class="email-capability"><input type="checkbox" value="EMAIL_SEND" data-email-capability checked disabled /><span><strong>Nach Freigabe senden</strong><small>Versand bleibt immer an die vorgesehene Freigabe gebunden</small></span></label></div><p class="email-preferences-note" id="emailPreferencesStatus" aria-live="polite">Nach bestätigter Verbindung kannst du diese Funktionen einzeln ein- oder ausschalten.</p></div>'
must_replace(konto, old_block, new_block)

must_replace(js,'const CAPABILITIES = ["EMAIL_READ", "EMAIL_SEARCH", "EMAIL_ATTACHMENTS", "EMAIL_DRAFT", "EMAIL_SEND"];','const CAPABILITIES = ["EMAIL_READ", "EMAIL_SEARCH", "EMAIL_ATTACHMENTS", "EMAIL_DRAFT", "EMAIL_MAILBOX", "EMAIL_SEND"];')
needle='''  function normalizeConnection(body) {\n    if (body?.ok !== true) return null;\n    const state = String(body?.state || "").toUpperCase();\n    if (!STATES.includes(state)) return null;\n    const provider = body?.provider == null ? null : String(body.provider).toUpperCase();\n    if (provider !== null && provider !== "GOOGLE") return null;\n    const hint = String(body?.account_display_hint || "").trim();\n    return {\n      provider,\n      state,\n      capabilities: Array.isArray(body?.capabilities) ? body.capabilities.map(String).filter((v) => CAPABILITIES.includes(v)) : [],\n      account_display_hint: hint && /[•*]/.test(hint) ? hint.slice(0, 180) : null,\n      reauth_required: body?.reauth_required === true,\n      scope_required: body?.scope_required === true\n    };\n  }\n'''
addition=needle+'''\n  function normalizePreferences(body) {\n    if (body?.ok !== true || !body.preferences || typeof body.preferences !== "object" || Array.isArray(body.preferences)) return null;\n    const available = new Set(Array.isArray(body.available_capabilities) ? body.available_capabilities.map(String).filter((v) => CAPABILITIES.includes(v)) : []);\n    const out = Object.fromEntries(CAPABILITIES.map((capability) => [capability, available.has(capability) && body.preferences[capability] === true]));\n    if (!out.EMAIL_READ) {\n      out.EMAIL_SEARCH = false;\n      out.EMAIL_ATTACHMENTS = false;\n    }\n    return out;\n  }\n'''
must_replace(js,needle,addition)
must_replace(js,'    normalizeConnection,\n    gatewayRequest,','    normalizeConnection,\n    normalizePreferences,\n    gatewayRequest,')
must_replace(js,'  const runtimeNote = document.getElementById("emailRuntimeNote");','  const runtimeNote = document.getElementById("emailRuntimeNote");\n  const preferencesStatus = document.getElementById("emailPreferencesStatus");')
must_replace(js,'  let providers = [];\n  let connection = null;\n  let loading = false;\n  let loaded = false;','  let providers = [];\n  let connection = null;\n  let preferences = null;\n  let savingPreferences = false;\n  let loading = false;\n  let loaded = false;')
old_render='''  function renderCapabilities(values = CAPABILITIES) {\n    const allowed = new Set(Array.isArray(values) && values.length ? values : CAPABILITIES);\n    capabilityInputs.forEach((input) => {\n      input.checked = allowed.has(String(input.value));\n      input.disabled = connection?.state === "CONNECTED" || !googleAvailable();\n    });\n  }\n'''
new_render='''  function renderCapabilities() {\n    const connected = String(connection?.state || "") === "CONNECTED";\n    const available = new Set(Array.isArray(connection?.capabilities) ? connection.capabilities : []);\n    capabilityInputs.forEach((input) => {\n      const key = String(input.value);\n      input.checked = connected ? preferences?.[key] === true : false;\n      input.disabled = !connected || !available.has(key) || savingPreferences;\n      input.closest(".email-capability")?.classList.toggle("is-disabled", input.disabled);\n    });\n    if (preferencesStatus) {\n      preferencesStatus.textContent = !connected\n        ? "Nach bestätigter Verbindung kannst du diese Funktionen einzeln ein- oder ausschalten."\n        : savingPreferences\n          ? "Einstellungen werden sicher gespeichert …"\n          : "Änderungen gelten für deinen verbundenen Gmail-Zugang in allen NAHWERK-Kanälen.";\n    }\n  }\n'''
must_replace(js,old_render,new_render)
must_replace(js,'      stateMeta.textContent = "Dein Concierge kann E-Mails lesen und suchen, Entwürfe vorbereiten und nur nach der vorgesehenen Freigabe senden.";','      stateMeta.textContent = "Dein Concierge nutzt nur die Funktionen, die du unten aktiviert hast. Senden bleibt zusätzlich an die vorgesehene Freigabe gebunden.";')
old_load='''      const [providerData, connectionData] = await Promise.all([\n        request("/email/providers"),\n        request("/email/connection")\n      ]);\n      providers = normalizeProviderList(providerData);\n      connection = normalizeConnection(connectionData) || { state: "ERROR", provider: "GOOGLE", capabilities: [], account_display_hint: null };\n      renderProviders();\n      renderConnection();\n      loaded = true;\n'''
new_load='''      const [providerData, connectionData, preferenceData] = await Promise.all([\n        request("/email/providers"),\n        request("/email/connection"),\n        request("/email/preferences")\n      ]);\n      providers = normalizeProviderList(providerData);\n      connection = normalizeConnection(connectionData) || { state: "ERROR", provider: "GOOGLE", capabilities: [], account_display_hint: null };\n      preferences = normalizePreferences(preferenceData);\n      if (connection?.state === "CONNECTED" && !preferences) throw new Error("EMAIL_REQUEST_INVALID");\n      renderProviders();\n      renderConnection();\n      loaded = true;\n'''
must_replace(js,old_load,new_load)
insert_before='''  connectButton.addEventListener("click", () => begin("/email/connect"));\n'''
save_fn='''  async function savePreferences(changedInput) {\n    if (String(connection?.state || "") !== "CONNECTED" || savingPreferences) return;\n    if (String(changedInput?.value || "") === "EMAIL_READ" && changedInput.checked === false) {\n      for (const input of capabilityInputs) {\n        if (input.value === "EMAIL_SEARCH" || input.value === "EMAIL_ATTACHMENTS") input.checked = false;\n      }\n    }\n    savingPreferences = true;\n    renderCapabilities();\n    try {\n      const requested = Object.fromEntries(capabilityInputs.map((input) => [String(input.value), input.checked === true]));\n      const data = await request("/email/preferences", { method: "POST", body: { preferences: requested } });\n      const next = normalizePreferences(data);\n      if (!next) throw new Error("EMAIL_REQUEST_INVALID");\n      preferences = next;\n    } catch (error) {\n      loaded = false;\n      await load(true);\n      return;\n    } finally {\n      savingPreferences = false;\n      renderCapabilities();\n    }\n  }\n\n  capabilityInputs.forEach((input) => input.addEventListener("change", () => savePreferences(input)));\n\n'''+insert_before
must_replace(js,insert_before,save_fn)

must_replace(css,'.email-capabilities{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}', '.email-capabilities{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}')
append_css='''\n.email-preferences-note{margin:10px 0 0;color:#aeb7c2;font-size:12px;line-height:1.5}.email-capability{align-items:center;cursor:pointer;transition:border-color .18s ease,background .18s ease,opacity .18s ease}.email-capability>span{display:grid;gap:2px;min-width:0}.email-capability strong{font-size:12px;color:#f2f4f7}.email-capability small{font-size:11px;line-height:1.35;color:#aeb7c2}.email-capability input[data-email-capability]{-webkit-appearance:none;appearance:none;position:relative;width:42px;height:24px;flex:0 0 42px;margin:0;border:1px solid rgba(133,154,182,.38);border-radius:999px;background:rgba(255,255,255,.08);cursor:pointer;transition:background .18s ease,border-color .18s ease,box-shadow .18s ease}.email-capability input[data-email-capability]::after{content:"";position:absolute;top:2px;left:2px;width:18px;height:18px;border-radius:50%;background:#eef1f5;box-shadow:0 2px 7px rgba(0,0,0,.28);transition:transform .18s cubic-bezier(.2,.8,.2,1)}.email-capability input[data-email-capability]:checked{border-color:#d4af37;background:#d4af37;box-shadow:0 0 0 1px rgba(212,175,55,.12)}.email-capability input[data-email-capability]:checked::after{transform:translateX(18px)}.email-capability input[data-email-capability]:focus-visible{outline:3px solid rgba(212,175,55,.34);outline-offset:3px}.email-capability.is-disabled{cursor:not-allowed;opacity:.55}.email-capability input[data-email-capability]:disabled{cursor:not-allowed}body.senior-product .email-capability strong,body[data-product="senioren"] .email-capability strong{color:#181713}body.senior-product .email-capability small,body[data-product="senioren"] .email-capability small,body.senior-product .email-preferences-note,body[data-product="senioren"] .email-preferences-note{color:#665f54}\n'''
Path(css).write_text(Path(css).read_text().rstrip()+append_css)

must_replace(test,'const allCaps=["EMAIL_READ","EMAIL_SEARCH","EMAIL_ATTACHMENTS","EMAIL_DRAFT","EMAIL_SEND"];','const allCaps=["EMAIL_READ","EMAIL_SEARCH","EMAIL_ATTACHMENTS","EMAIL_DRAFT","EMAIL_MAILBOX","EMAIL_SEND"];')
needle_test='''test("connection accepts exact states and only masked account hints",()=>{\n  const good=hooks.normalizeConnection({ok:true,provider:"GOOGLE",state:"CONNECTED",capabilities:allCaps,account_display_hint:"d•••@gmail.com"});\n  assert.equal(good.state,"CONNECTED");assert.equal(good.account_display_hint,"d•••@gmail.com");\n  assert.equal(hooks.normalizeConnection({ok:true,provider:"GOOGLE",state:"ACTIVE",capabilities:[]}),null);\n  assert.equal(hooks.normalizeConnection({ok:true,provider:"GOOGLE",state:"CONNECTED",capabilities:[],account_display_hint:"deniz@gmail.com"}).account_display_hint,null);\n});\n'''
addition_test=needle_test+'''\ntest("customer controls are server authoritative and read-off also disables search and attachments",()=>{\n  const allOn=Object.fromEntries(allCaps.map(k=>[k,true]));\n  const good=hooks.normalizePreferences({ok:true,available_capabilities:allCaps,preferences:allOn});\n  assert.equal(good.EMAIL_MAILBOX,true);assert.equal(good.EMAIL_SEND,true);\n  const restricted=hooks.normalizePreferences({ok:true,available_capabilities:allCaps,preferences:{...allOn,EMAIL_READ:false}});\n  assert.equal(restricted.EMAIL_READ,false);assert.equal(restricted.EMAIL_SEARCH,false);assert.equal(restricted.EMAIL_ATTACHMENTS,false);\n  assert.match(konto,/Endkunden-Steuerung/);assert.match(konto,/EMAIL_MAILBOX/);assert.match(js,/\\/email\\/preferences/);\n});\n'''
must_replace(test,needle_test,addition_test)

print("GMAIL_CUSTOMER_CONTROLS_UI_PATCH=READY")
