import unittest
from datetime import datetime,timedelta,timezone
from credential_security_core import *
NOW=datetime.now(timezone.utc)

def ref(**kw):
 d=dict(credential_id='cred_1',provider='Twilio',credential_type=CredentialType.SYSTEM_API_KEY,owner_type=OwnerType.PLATFORM,owner_id='nahwerk',environment=Environment.STAGING,scope=frozenset({'messaging'}),secret_store='vault',secret_reference='opaque://cred_1',status=CredentialStatus.ACTIVE,metadata={}); d.update(kw); return CredentialReference(**d)
def conn(**kw):
 d=dict(connection_id='pc1',provider='Gmail',person_id='p1',account_id='a1',environment=Environment.STAGING,credential_reference='cred_1',capabilities=frozenset({'mail.read'}),status=ConnectionStatus.CONNECTED,authorized_scopes=frozenset({'mail.read'})); d.update(kw); return ProviderConnection(**d)
class SecurityTests(unittest.TestCase):
 def test_01_no_secret(self): self.assertFalse(hasattr(ref(),'secret'))
 def test_02_api_key_rejected(self): self.assertRaises(ValueError,ref,metadata={'api_key':'x'})
 def test_03_password_rejected(self): self.assertRaises(ValueError,ref,metadata={'password':'x'})
 def test_04_access_token_rejected(self): self.assertRaises(ValueError,ref,metadata={'access_token':'x'})
 def test_05_refresh_token_rejected(self): self.assertRaises(ValueError,ref,metadata={'refresh_token':'x'})
 def test_06_client_secret_rejected(self): self.assertRaises(ValueError,ref,metadata={'client_secret':'x'})
 def test_07_platform_owner(self): self.assertEqual(ref().owner_type,OwnerType.PLATFORM)
 def test_08_person_owner(self): self.assertEqual(ref(owner_type=OwnerType.PERSON).owner_type,OwnerType.PERSON)
 def test_09_account_owner(self): self.assertEqual(ref(owner_type=OwnerType.ACCOUNT).owner_type,OwnerType.ACCOUNT)
 def test_10_staging(self): self.assertEqual(ref().environment,Environment.STAGING)
 def test_11_production(self): self.assertEqual(ref(environment=Environment.PRODUCTION).environment,Environment.PRODUCTION)
 def test_12_cross_env(self): self.assertRaises(PermissionError,assert_environment,ref(),Environment.PRODUCTION)
 def test_13_oauth(self): self.assertTrue(OAuthConnection('o','p','a','Microsoft',frozenset({'Mail.Read'}),ConnectionStatus.CONNECTED,'opaque:a','opaque:r',NOW+timedelta(hours=1),NOW).usable())
 def test_14_oauth_scopes(self): self.assertEqual(frozenset({'Mail.Read'}),OAuthConnection('o','p','a','Microsoft',frozenset({'Mail.Read'}),ConnectionStatus.CONNECTED,'a','r',None,NOW).scopes)
 def test_15_expired_token(self): self.assertFalse(OAuthConnection('o','p','a','Gmail',frozenset(),ConnectionStatus.CONNECTED,'a','r',NOW-timedelta(seconds=1),NOW).usable())
 def test_16_revoked_token(self): self.assertFalse(OAuthConnection('o','p','a','Gmail',frozenset(),ConnectionStatus.REVOKED,'a','r',None,NOW,NOW).usable())
 def test_17_disconnect(self): self.assertEqual(disconnect(conn()).status,ConnectionStatus.DISCONNECTED)
 def test_18_imap_ref(self): self.assertEqual(ref(credential_type=CredentialType.USER_IMAP_CREDENTIAL).credential_type,CredentialType.USER_IMAP_CREDENTIAL)
 def test_19_no_imap_plaintext(self): self.assertRaises(ValueError,ref,metadata={'password':'imap'})
 def test_20_twilio(self): self.assertEqual(ref().provider,'Twilio')
 def test_21_openai(self): self.assertEqual(ref(provider='OpenAI').provider,'OpenAI')
 def test_22_google_service(self): self.assertEqual(ref(provider='Google Document AI',credential_type=CredentialType.SERVICE_ACCOUNT).credential_type,CredentialType.SERVICE_ACCOUNT)
 def test_23_gmail_separate(self): self.assertIn('Gmail',SECRET_INVENTORY)
 def test_24_microsoft(self): self.assertIn('Microsoft',SECRET_INVENTORY)
 def test_25_aws(self): self.assertIn('IAM',SECRET_INVENTORY['AWS'][0])
 def test_26_azure(self): self.assertIn('Azure',SECRET_INVENTORY)
 def test_27_provider_connection(self): self.assertEqual(conn().provider,'Gmail')
 def test_28_pending(self): self.assertEqual(conn(status=ConnectionStatus.PENDING).status,ConnectionStatus.PENDING)
 def test_29_connected(self): self.assertEqual(conn().status,ConnectionStatus.CONNECTED)
 def test_30_expired(self): self.assertEqual(conn(status=ConnectionStatus.EXPIRED).status,ConnectionStatus.EXPIRED)
 def test_31_revoked(self): self.assertEqual(conn(status=ConnectionStatus.REVOKED).status,ConnectionStatus.REVOKED)
 def test_32_lifecycle(self): self.assertIn(CredentialStatus.ROTATING,list(CredentialStatus))
 def test_33_rotation(self): self.assertTrue(RotationPolicy(True,timedelta(days=90),timedelta(days=7)).rotation_required)
 def test_34_compromise(self): self.assertEqual(transition_credential(CredentialStatus.ACTIVE,CredentialStatus.COMPROMISED),CredentialStatus.COMPROMISED)
 def test_35_no_reactivation(self): self.assertRaises(ValueError,transition_credential,CredentialStatus.COMPROMISED,CredentialStatus.ACTIVE)
 def test_36_audit_redaction(self): self.assertRaises(ValueError,audit_event,'x',secret='bad')
 def test_37_log_redaction(self): self.assertEqual(redact({'token':'x'})['token'],'[REDACTED]')
 def test_38_auth_redaction(self): self.assertEqual(redact({'authorization':'Bearer x'})['authorization'],'[REDACTED]')
 def test_39_cookie_redaction(self): self.assertEqual(redact({'cookie':'x'})['cookie'],'[REDACTED]')
 def test_40_n8n_safe_error(self): self.assertNotIn('secret',safe_error('x','c',Environment.STAGING,'timeout'))
 def test_41_own_connection(self): self.assertTrue(can_manage_connection('p1',conn()))
 def test_42_foreign_denied(self): self.assertFalse(can_manage_connection('p2',conn()))
 def test_43_family_no_secret(self): self.assertNotIn('secret.read',END_USER_SCOPES)
 def test_44_no_secret_read(self): self.assertRaises(PermissionError,validate_end_user_scope,'secret.read')
 def test_45_env_isolation(self): self.assertTrue(assert_environment(ref(),Environment.STAGING))
 def test_46_staging_redirect_boundary(self): self.assertNotEqual(Environment.STAGING,Environment.PRODUCTION)
 def test_47_prod_redirect_boundary(self): self.assertEqual(Environment.PRODUCTION.value,'PRODUCTION')
 def test_48_cutover(self): self.assertTrue(CutoverGate(*([True]*9)).ready)
 def test_49_revoked_blocks(self): self.assertRaises(PermissionError,assert_environment,ref(status=CredentialStatus.REVOKED),Environment.STAGING)
 def test_50_expired_blocks(self): self.assertRaises(PermissionError,assert_environment,ref(status=CredentialStatus.EXPIRED),Environment.STAGING)
 def test_51_missing_credential(self): self.assertRaises(ValueError,ref,secret_reference='')
 def test_52_provider_unavailable(self): self.assertEqual(safe_error('x','c',Environment.TEST,'provider_unavailable')['error_category'],'provider_unavailable')
 def test_53_idempotent_disconnect(self):
  once=disconnect(conn()); self.assertIs(disconnect(once),once)
 def test_54_rotation_grace(self): self.assertEqual(RotationPolicy(True,None,None,timedelta(minutes=5)).grace_period,timedelta(minutes=5))
 def test_55_old_revoked(self): self.assertEqual(transition_credential(CredentialStatus.ROTATING,CredentialStatus.REVOKED),CredentialStatus.REVOKED)
 def test_56_audit_ids_only(self): self.assertEqual(set(audit_event('credential_failed',credential_id='c',provider='p',environment='STAGING',status='ERROR',error_category='x')),{'event','credential_id','provider','environment','status','error_category'})
 def test_57_no_prod_secret_fixture(self): self.assertNotIn('value',ref(environment=Environment.PRODUCTION).__dict__)
 def test_58_synthetic_fixtures(self): self.assertTrue(ref(owner_id='synthetic').owner_id=='synthetic')
 def test_59_no_live_provider(self): self.assertFalse(any(k in globals() for k in ('requests','httpx','boto3')))
 def test_60_no_prod_mutation(self): self.assertFalse(hasattr(ref(),'save'))
 def test_61_inventory(self): self.assertGreaterEqual(len(SECRET_INVENTORY),17)
 def test_62_memory_separation(self): self.assertNotIn('memory',ref().__dict__)
 def test_63_identity_separation(self): self.assertNotIn('identity',ref().__dict__)
 def test_64_authorization_separation(self): self.assertNotIn('authorization',ref().__dict__)
 def test_65_metadata_separation(self): self.assertIsInstance(ref().metadata,dict)
 def test_66_other_secret_class(self): self.assertIn(CredentialType.OTHER,list(CredentialType))
 def test_67_webhook_class(self): self.assertIn(CredentialType.WEBHOOK_SECRET,list(CredentialType))
 def test_68_encryption_ref(self): self.assertIn(CredentialType.ENCRYPTION_KEY_REFERENCE,list(CredentialType))
 def test_69_customer_owner(self): self.assertIn(OwnerType.CUSTOMER,list(OwnerType))
 def test_70_provider_owner(self): self.assertIn(OwnerType.PROVIDER_CONNECTION,list(OwnerType))
if __name__=='__main__': unittest.main(verbosity=2)
