import unittest
from datetime import datetime,timedelta
from daily_brief_delivery import *
NOW=datetime(2026,8,26,12,0)
def request(channel=Channel.WHATSAPP,policy=None,auth=None,falls=(Channel.APP_PUSH,)):
 p=policy or DailyBriefDeliveryPolicy(); key=DeliveryPlanner.deterministic_id('p','2026-08-26','MORNING','snap',channel)
 return DailyBriefDeliveryRequest('dr','b','p','a','MORNING',channel,falls,'Europe/Berlin',NOW,p,auth or AuthorizationContext(),key,NOW)
class T(unittest.TestCase):
 def test_01_whatsapp_plan(self): self.assertEqual(DeliveryPlanner.choose_channel(request()),Channel.WHATSAPP)
 def test_02_push_plan(self): self.assertEqual(DeliveryPlanner.choose_channel(request(Channel.APP_PUSH)),Channel.APP_PUSH)
 def test_03_email_disabled(self): self.assertIsNone(DeliveryPlanner.choose_channel(request(Channel.EMAIL)))
 def test_04_email_enabled(self): self.assertEqual(DeliveryPlanner.choose_channel(request(Channel.EMAIL,DailyBriefDeliveryPolicy(email_allowed=True,allowed_channels=(Channel.EMAIL,)))),Channel.EMAIL)
 def test_05_voice_disabled(self): self.assertIsNone(DeliveryPlanner.choose_channel(request(Channel.VOICE)))
 def test_06_voice_enabled(self): self.assertEqual(DeliveryPlanner.choose_channel(request(Channel.VOICE,DailyBriefDeliveryPolicy(voice_allowed=True,allowed_channels=(Channel.VOICE,)))),Channel.VOICE)
 def test_07_web(self): self.assertEqual(DeliveryPlanner.choose_channel(request(Channel.WEB)),Channel.WEB)
 def test_08_preferred_blocked(self): self.assertIsNone(DeliveryPlanner.choose_channel(request(Channel.WHATSAPP,DailyBriefDeliveryPolicy(allowed_channels=(Channel.WEB,)))))
 def test_09_fallback(self): self.assertEqual(DeliveryPlanner.fallback(request(),Channel.WHATSAPP),Channel.APP_PUSH)
 def test_10_no_fallback(self): self.assertIsNone(DeliveryPlanner.fallback(request(falls=()),Channel.WHATSAPP))
 def test_11_no_voice_fallback(self): self.assertIsNone(DeliveryPlanner.fallback(request(falls=(Channel.VOICE,)),Channel.WHATSAPP))
 def test_12_quiet_23(self): self.assertTrue(DeliveryPlanner.in_quiet_hours(datetime(2026,8,26,23),('22:00','08:00')))
 def test_13_quiet_07(self): self.assertTrue(DeliveryPlanner.in_quiet_hours(datetime(2026,8,26,7),('22:00','08:00')))
 def test_14_not_quiet(self): self.assertFalse(DeliveryPlanner.in_quiet_hours(NOW,('22:00','08:00')))
 def test_15_timezone(self): self.assertEqual(request().timezone,'Europe/Berlin')
 def test_16_weekend_policy(self): self.assertEqual(request().delivery_policy.weekend_policy,'USER_PREFERENCE')
 def test_17_only_relevant(self): self.assertTrue(request().delivery_policy.only_if_relevant)
 def test_18_all_clear_off(self): self.assertFalse(request().delivery_policy.send_all_clear)
 def test_19_idempotency_same(self): self.assertEqual(request().idempotency_key,request().idempotency_key)
 def test_20_idempotency_channel(self): self.assertNotEqual(request().idempotency_key,request(Channel.APP_PUSH).idempotency_key)
 def test_21_store_duplicate(self):
  s=ClaimStore(); r=DeliveryRecord(request()); self.assertTrue(s.put(r)); self.assertFalse(s.put(DeliveryRecord(request())))
 def test_22_claim(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); self.assertTrue(s.claim(r.request.idempotency_key,'w',NOW,NOW+timedelta(minutes=5)))
 def test_23_second_worker_blocked(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.claim(r.request.idempotency_key,'w1',NOW,NOW+timedelta(minutes=5)); self.assertFalse(s.claim(r.request.idempotency_key,'w2',NOW,NOW+timedelta(minutes=5)))
 def test_24_expired_lease_claim(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.claim(r.request.idempotency_key,'w1',NOW,NOW+timedelta(minutes=1)); self.assertTrue(s.claim(r.request.idempotency_key,'w2',NOW+timedelta(minutes=2),NOW+timedelta(minutes=7)))
 def test_25_attempt(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.claim(r.request.idempotency_key,'w',NOW,NOW+timedelta(minutes=1)); self.assertEqual(r.attempt,1)
 def test_26_release(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.claim(r.request.idempotency_key,'w',NOW,NOW+timedelta(minutes=1)); s.release(r.request.idempotency_key); self.assertEqual(r.state,DeliveryState.SCHEDULED)
 def test_27_complete(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.complete(r.request.idempotency_key); self.assertEqual(r.state,DeliveryState.SENT)
 def test_28_delivered(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.complete(r.request.idempotency_key,Receipt.DELIVERED); self.assertEqual(r.state,DeliveryState.DELIVERED)
 def test_29_timeout_retry(self): self.assertTrue(DeliveryPlanner.retryable('TIMEOUT',RetryPolicy()))
 def test_30_rate_retry(self): self.assertTrue(DeliveryPlanner.retryable('RATE_LIMIT',RetryPolicy()))
 def test_31_temp_retry(self): self.assertTrue(DeliveryPlanner.retryable('TEMPORARY_PROVIDER_ERROR',RetryPolicy()))
 def test_32_invalid_no_retry(self): self.assertFalse(DeliveryPlanner.retryable('INVALID_DESTINATION',RetryPolicy()))
 def test_33_revoked_no_retry(self): self.assertFalse(DeliveryPlanner.retryable('REVOKED_AUTHORIZATION',RetryPolicy()))
 def test_34_disabled_no_retry(self): self.assertFalse(DeliveryPlanner.retryable('DISABLED_DELIVERY',RetryPolicy()))
 def test_35_expired_no_retry(self): self.assertFalse(DeliveryPlanner.retryable('EXPIRED_BRIEF',RetryPolicy()))
 def test_36_auth_self(self): self.assertTrue(DeliveryPlanner.authorize(request(),Sensitivity.NORMAL))
 def test_37_auth_disabled(self): self.assertFalse(DeliveryPlanner.authorize(request(policy=DailyBriefDeliveryPolicy(enabled=False)),Sensitivity.NORMAL))
 def test_38_family_no_scope(self): self.assertFalse(DeliveryPlanner.authorize(request(auth=AuthorizationContext(frozenset(),False)),Sensitivity.NORMAL,True))
 def test_39_family_scope(self): self.assertTrue(DeliveryPlanner.authorize(request(auth=AuthorizationContext(frozenset({'brief.receive'}),False)),Sensitivity.NORMAL,True))
 def test_40_restricted_block(self): self.assertFalse(DeliveryPlanner.authorize(request(),Sensitivity.RESTRICTED))
 def test_41_push_redact(self): self.assertEqual(Renderer.render(Channel.APP_PUSH,{'top_items':['secret']},Sensitivity.SENSITIVE)['body'],'Ihre Tagesübersicht ist verfügbar.')
 def test_42_push_normal(self): self.assertEqual(Renderer.render(Channel.APP_PUSH,{'top_items':['Termin']})['body'],'Termin')
 def test_43_wa_max3(self): self.assertNotIn('d',Renderer.render(Channel.WHATSAPP,{'headline':'h','top_items':['a','b','c','d']})['text'].split('Weitere')[0])
 def test_44_wa_more(self): self.assertIn('Weitere 1 Punkte',Renderer.render(Channel.WHATSAPP,{'headline':'h','top_items':['a','b','c','d']})['text'])
 def test_45_email_subject(self): self.assertEqual(Renderer.render(Channel.EMAIL,{'headline':'h','top_items':[]})['subject'],'Ihre NAHWERK Tagesübersicht')
 def test_46_voice_cedar(self): self.assertEqual(Renderer.render(Channel.VOICE,{'headline':'h','top_items':[]})['voice'],'cedar')
 def test_47_voice_marin(self): self.assertEqual(Renderer.render(Channel.VOICE,{'headline':'h','top_items':[],'voice':'marin'})['voice'],'marin')
 def test_48_web_more(self): self.assertEqual(Renderer.render(Channel.WEB,{'headline':'h','top_items':['a','b','c','d']})['more_count'],1)
 def test_49_caps_wa_audio(self): self.assertTrue(CAPABILITIES[Channel.WHATSAPP].supports_audio)
 def test_50_caps_push_no_read(self): self.assertFalse(CAPABILITIES[Channel.APP_PUSH].supports_read_receipts)
 def test_51_caps_email_html(self): self.assertTrue(CAPABILITIES[Channel.EMAIL].supports_html)
 def test_52_caps_voice_audio(self): self.assertTrue(CAPABILITIES[Channel.VOICE].supports_audio)
 def test_53_caps_web_links(self): self.assertTrue(CAPABILITIES[Channel.WEB].supports_links)
 def test_54_fixture_no_live(self): self.assertIsInstance(FixtureDeliveryProvider(Channel.WHATSAPP),FixtureDeliveryProvider)
 def test_55_fixture_send(self): self.assertEqual(FixtureDeliveryProvider(Channel.WHATSAPP).send({'x':1})['receipt'],Receipt.SENT)
 def test_56_no_live_flags(self): self.assertTrue(all(v is False for v in FEATURE_FLAGS.values()))
 def test_57_on_demand_flag(self): self.assertIn('daily_brief.on_demand',FEATURE_FLAGS)
 def test_58_scheduled_flag(self): self.assertIn('daily_brief.scheduled_delivery',FEATURE_FLAGS)
 def test_59_max_delivery(self): self.assertEqual(request().delivery_policy.max_deliveries_per_day,2)
 def test_60_retry_max(self): self.assertEqual(request().delivery_policy.retry_policy.max_attempts,3)
 def test_61_pause_active(self): self.assertTrue(TemporaryDeliveryPause(NOW-timedelta(hours=1),NOW+timedelta(hours=1),'x').active(NOW))
 def test_62_pause_expired(self): self.assertFalse(TemporaryDeliveryPause(NOW-timedelta(hours=2),NOW-timedelta(hours=1),'x').active(NOW))
 def test_63_cancel(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.cancel(r.request.idempotency_key); self.assertEqual(r.state,DeliveryState.CANCELLED)
 def test_64_cancel_audit(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.cancel(r.request.idempotency_key); self.assertIn('delivery_cancelled',r.audit)
 def test_65_audit_no_content(self):
  s=ClaimStore(); r=DeliveryRecord(request()); s.put(r); s.claim(r.request.idempotency_key,'w',NOW,NOW+timedelta(minutes=1)); self.assertEqual(r.audit,['delivery_claimed'])
 def test_66_provider_calls_zero(self): self.assertEqual(DeliveryRecord(request()).provider_calls,0)
 def test_67_renderer_no_provider(self): self.assertEqual(DeliveryRecord(request()).provider_calls,0)
 def test_68_receipt_unknown(self): self.assertEqual(DeliveryRecord(request()).receipt,Receipt.UNKNOWN)
 def test_69_read_capability_not_invented(self): self.assertFalse(CAPABILITIES[Channel.EMAIL].supports_read_receipts)
 def test_70_rollout(self): self.assertEqual(len(ROLLOUT),5)
 def test_71_phase0(self): self.assertIn('Core only',ROLLOUT[0])
 def test_72_phase2_optin(self): self.assertIn('opt-in',ROLLOUT[2])
 def test_73_no_voice_auto_fallback(self): self.assertNotEqual(DeliveryPlanner.fallback(request(falls=(Channel.VOICE,Channel.APP_PUSH)),Channel.WHATSAPP),Channel.VOICE)
 def test_74_state_initial(self): self.assertEqual(DeliveryRecord(request()).state,DeliveryState.PLANNED)
 def test_75_states_complete(self): self.assertEqual(len(DeliveryState),11)
 def test_76_receipts(self): self.assertEqual(len(Receipt),6)
 def test_77_policy_voice_false(self): self.assertFalse(request().delivery_policy.voice_allowed)
 def test_78_policy_email_false(self): self.assertFalse(request().delivery_policy.email_allowed)
 def test_79_family_scope_required(self): self.assertTrue(request().delivery_policy.family_scope_required)
 def test_80_core_compatibility_boundary(self): self.assertEqual(request().brief_id,'b')
if __name__=='__main__': unittest.main()
