import unittest
from datetime import datetime,date,timedelta
from daily_brief_core import *
NOW=datetime(2026,8,26,8,0)
def req(mode=RequestedMode.ON_DEMAND,auth=None,prefs=None): return DailyBriefRequest('r','p','p','p','a',date(2026,8,26),requested_mode=mode,authorization_context=auth or AuthorizationContext(),preferences=prefs or {})
def item(n=1,src=SourceType.REMINDER,**kw):
    base=dict(item_id=f'i{n}',source_type=src,source_id=f's{n}',category='GENERAL',title=f'T{n}',short_summary=f'Punkt {n}',source_updated_at=NOW); base.update(kw); return BriefItem(**base)
class T(unittest.TestCase):
 def setUp(self): self.c=DailyBriefCore()
 def b(self,items,mode=RequestedMode.ON_DEMAND,auth=None,delivery=None): return self.c.build(req(mode,auth),items,NOW,delivery)
 def test_01_morning(self): self.assertIn('Guten Morgen',self.b([item()],RequestedMode.MORNING).headline)
 def test_02_evening(self): self.assertIn('Guten Abend',self.b([item()],RequestedMode.EVENING).headline)
 def test_03_on_demand(self): self.assertEqual(self.b([item()]).headline,'Hier ist Ihre Übersicht.')
 def test_04_week(self): self.assertIn('sieben Tagen',self.b([item(event_time=NOW+timedelta(days=2))],RequestedMode.WEEK_PREVIEW).headline)
 def test_05_empty(self): self.assertEqual(len(self.b([]).top_items),0)
 def test_06_one_reminder(self): self.assertEqual(len(self.b([item()]).top_items),1)
 def test_07_multi_reminder(self): self.assertEqual(len(self.b([item(1),item(2)]).top_items),2)
 def test_08_appointment_today(self): self.assertIn('TODAY',self.b([item(src=SourceType.APPOINTMENT,event_time=NOW+timedelta(hours=2))]).sections)
 def test_09_appointment_tomorrow(self): self.assertIn('UPCOMING',self.b([item(src=SourceType.APPOINTMENT,event_time=NOW+timedelta(days=1))]).sections)
 def test_10_deadline_today(self): self.assertIn('DEADLINES',self.b([item(deadline=NOW+timedelta(hours=2))]).sections)
 def test_11_overdue(self): self.assertEqual(len(self.b([item(deadline=NOW-timedelta(hours=1))]).top_items),1)
 def test_12_mail(self): self.assertIn('IMPORTANT_EMAILS',self.b([item(src=SourceType.EMAIL,category='ACTION_REQUIRED')]).sections)
 def test_13_newsletter(self): self.assertEqual(len(self.b([item(src=SourceType.EMAIL,category='NEWSLETTER')]).top_items),0)
 def test_14_fraud(self): self.assertEqual(self.b([item(src=SourceType.FRAUD,priority=Priority.HIGH)]).important_count,1)
 def test_15_case(self): self.assertEqual(len(self.b([item(src=SourceType.CASE)]).top_items),1)
 def test_16_wait_provider(self): self.assertIn('Anbieters',self.b([item(waiting_for='WAITING_FOR_PROVIDER')]).summary)
 def test_17_wait_approval(self): self.assertIn('Freigabe',self.b([item(waiting_for='WAITING_FOR_APPROVAL')]).summary)
 def test_18_wait_human(self): self.assertIn('persönliche Bearbeitung',self.b([item(waiting_for='WAITING_FOR_HUMAN')]).summary)
 def test_19_restaurant(self): self.assertEqual(self.b([item(src=SourceType.RESTAURANT)]).top_items[0].source_type,SourceType.RESTAURANT)
 def test_20_restaurant_approval(self): self.assertEqual(self.b([item(src=SourceType.RESTAURANT,action_required=True)]).action_required_count,1)
 def test_21_service(self): self.assertEqual(self.b([item(src=SourceType.SERVICE)]).top_items[0].source_type,SourceType.SERVICE)
 def test_22_mobility(self): self.assertEqual(self.b([item(src=SourceType.MOBILITY,event_time=NOW+timedelta(hours=1))]).next_event.source_type,SourceType.MOBILITY)
 def test_23_provider_switch(self): self.assertEqual(len(self.b([item(src=SourceType.PROVIDER_SWITCH)]).top_items),1)
 def test_24_family_self(self): self.assertEqual(len(self.b([item(src=SourceType.EMAIL)]).top_items),1)
 def test_25_family_no_scope(self): self.assertEqual(len(self.b([item(src=SourceType.EMAIL)],auth=AuthorizationContext(frozenset(),False)).top_items),0)
 def test_26_family_scope(self): self.assertEqual(len(self.b([item(src=SourceType.EMAIL)],auth=AuthorizationContext(frozenset({'brief.read','email.read'}),False)).top_items),1)
 def test_27_normal(self): self.assertEqual(self.b([item(sensitivity=Sensitivity.NORMAL)]).top_items[0].short_summary,'Punkt 1')
 def test_28_sensitive_redaction(self): self.assertIn('medizinischen',self.b([item(category='MEDICAL',sensitivity=Sensitivity.SENSITIVE)]).summary)
 def test_29_restricted(self): self.assertEqual(len(self.b([item(sensitivity=Sensitivity.RESTRICTED)],auth=AuthorizationContext(frozenset({'brief.read'}),False)).top_items),0)
 def test_30_memory_pref(self): self.assertEqual(req(prefs={'appointments_first':True}).preferences['appointments_first'],True)
 def test_31_memory_no_fact(self): self.assertEqual(self.b([]).top_items,[])
 def test_32_max3(self): self.assertEqual(len(self.b([item(i) for i in range(5)]).top_items),3)
 def test_33_more(self): self.assertEqual(self.b([item(i) for i in range(5)]).optional_more_count,2)
 def test_34_priority(self): self.assertEqual(self.b([item(1),item(2,priority=Priority.HIGH)]).top_items[0].item_id,'i2')
 def test_35_deadline_before_newsletter(self): self.assertEqual(self.b([item(1,deadline=NOW),item(2,src=SourceType.EMAIL,category='NEWSLETTER')]).top_items[0].item_id,'i1')
 def test_36_safety(self): self.assertIn('SAFETY',self.b([item(safety=True)]).sections)
 def test_37_safety_no_action(self): self.assertEqual(self.b([item(safety=True)]).action_required_count,0)
 def test_38_reminder_appt_dedup(self): self.assertEqual(len(self.b([item(1,correlation_key='x'),item(2,src=SourceType.APPOINTMENT,correlation_key='x')]).sections['OTHER']),1)
 def test_39_case_appt_dedup(self): self.assertEqual(len(self.b([item(1,src=SourceType.CASE,correlation_key='x'),item(2,src=SourceType.APPOINTMENT,correlation_key='x')]).top_items),1)
 def test_40_refs(self): self.assertEqual(len(self.b([item(1,correlation_key='x'),item(2,correlation_key='x')]).top_items[0].source_references),2)
 def test_41_conflicting_time(self): self.assertTrue(self.b([item(1,correlation_key='x',event_time=NOW),item(2,correlation_key='x',event_time=NOW+timedelta(hours=1))]).top_items[0].conflicting)
 def test_42_conflicting_amount(self): self.assertTrue(self.b([item(1,correlation_key='x',amount=1),item(2,correlation_key='x',amount=2)]).top_items[0].conflicting)
 def test_43_stale_provider(self): self.assertEqual(len(self.b([item(src=SourceType.RESTAURANT,source_updated_at=NOW-timedelta(hours=7))]).top_items),0)
 def test_44_fresh(self): self.assertEqual(len(self.b([item(src=SourceType.RESTAURANT,source_updated_at=NOW-timedelta(hours=1))]).top_items),1)
 def test_45_low_conf(self): self.assertEqual(len(self.b([item(confidence=.2)]).top_items),0)
 def test_46_high_conf(self): self.assertEqual(self.b([item(confidence=.9)]).confidence,.9)
 def test_47_only_relevant(self): self.assertEqual(self.b([],delivery=BriefDeliveryPreference(only_if_relevant=True)).summary,'Für heute ist nichts Dringendes offen.')
 def test_48_quiet(self): self.assertEqual(self.b([],delivery=BriefDeliveryPreference(quiet_hours=('21:00','08:00'))).metadata['delivery_policy']['quiet_hours'],('21:00','08:00'))
 def test_49_weekend(self): self.assertEqual(self.b([],delivery=BriefDeliveryPreference(weekend_policy='SKIP')).metadata['delivery_policy']['weekend_policy'],'SKIP')
 def test_50_no_delivery(self): self.assertFalse(self.b([]).metadata['automatic_delivery'])
 def test_51_whatsapp(self): self.assertIn('Möchten',ChannelRenderer.render(self.b([item()]),'WHATSAPP'))
 def test_52_app(self): self.assertIn('Punkt',ChannelRenderer.render(self.b([item()]),'APP'))
 def test_53_voice(self): self.assertIn('Übersicht',ChannelRenderer.render(self.b([item()]),'VOICE'))
 def test_54_channel_neutral(self): self.assertEqual(ChannelRenderer.render(self.b([item()]),'WEB'),ChannelRenderer.render(self.b([item()]),'EMAIL'))
 def test_55_idempotency(self): self.assertEqual(self.b([item()]).brief_id,self.b([item()]).brief_id)
 def test_56_snapshot(self): self.assertEqual(self.b([item()]).metadata['data_snapshot'],self.b([item()]).metadata['data_snapshot'])
 def test_57_audit_privacy(self): self.assertNotIn('body',str(self.b([item()]).metadata['audit']))
 def test_58_no_llm(self): self.assertFalse(self.b([]).metadata['llm_business_logic'])
 def test_59_cost(self): self.assertEqual(self.b([]).metadata['external_provider_calls'],0)
 def test_60_no_provider(self): self.assertEqual(self.b([item(src=SourceType.PROVIDER_SWITCH)]).metadata['external_provider_calls'],0)
 def test_61_synthetic_data(self): self.assertEqual(req().person_id,'p')
 def test_62_no_production(self): self.assertFalse(self.b([]).metadata['automatic_delivery'])
 def test_63_action(self): self.assertIn('ACTION_REQUIRED',self.b([item(action_required=True)]).sections)
 def test_64_waiting(self): self.assertIn('WAITING',self.b([item(waiting_for='WAITING_FOR_USER')]).sections)
 def test_65_senior_ux(self): self.assertEqual(self.b([item(i) for i in range(5)]).optional_more_count,2)
 def test_66_conflict_wording(self): self.assertIn('widersprüchliche',self.b([item(1,correlation_key='x',amount=1),item(2,correlation_key='x',amount=2)]).summary)
 def test_67_restricted_with_scope(self): self.assertEqual(len(self.b([item(sensitivity=Sensitivity.RESTRICTED)],auth=AuthorizationContext(frozenset({'brief.read','reminder.read','restricted.read'}),False)).top_items),1)
 def test_68_bad_channel(self): self.assertRaises(ValueError,ChannelRenderer.render,self.b([]),'SMS')
 def test_69_evening_done_filtered(self): self.assertEqual(len(self.b([item(status='DONE')],RequestedMode.EVENING).top_items),0)
 def test_70_week_outside_filtered(self): self.assertEqual(len(self.b([item(event_time=NOW+timedelta(days=8))],RequestedMode.WEEK_PREVIEW).top_items),0)
if __name__=='__main__': unittest.main()
