import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import { webcrypto } from "node:crypto";
const js=fs.readFileSync("assets/family-owner-sponsored-access.js","utf8");
const css=fs.readFileSync("assets/family-owner-sponsored-access.css","utf8");
const konto=fs.readFileSync("konto.html","utf8");
const carousel=fs.readFileSync("assets/concierge-carousel.js","utf8");
const email=fs.readFileSync("assets/email-account-integration.js","utf8");
const phone=fs.readFileSync("assets/telephone-reception-product.js","utf8");
const home=fs.readFileSync("index.html","utf8");
function hooks(){const sandbox={console,URL,TextEncoder,Uint8Array,crypto:webcrypto};vm.createContext(sandbox);vm.runInContext(js,sandbox);return sandbox.NAHWERKFamilyOwnerTestHooks}
function storage(){const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function response(status,body){return {status,ok:status>=200&&status<300,json:async()=>body}}
const h=hooks(),token="x".repeat(40);
const entitlements=Object.fromEntries(h.FEATURE_CODES.map(code=>[code,1]));
const input={first_name:"Ayse",last_name:"Example",relationship:"MOTHER",whatsapp_number:"+491700000011",preferred_language:"tr",concierge_choice:"leyla",form_of_address:"DU",personal_message:"Hallo",contact_consent_attested:true,entitlements:h.buildEntitlements(entitlements)};

test("normal user cannot see OWNER controls by default",()=>{assert.match(konto,/id="familyOwnerPanel" hidden/);assert.equal(h.operatorContextAllowed({ok:true,operator:{role:"MEMBER",can_manage_sponsored_people:true},browser_actor_authority:false}),false)});
test("server OWNER context alone enables controls",()=>{assert.equal(h.operatorContextAllowed({ok:true,operator:{role:"OWNER",can_manage_sponsored_people:true,can_manage_sponsored_entitlements:true},browser_actor_authority:false}),true);assert.equal(h.operatorContextAllowed({ok:true,operator:{role:"OWNER",can_manage_sponsored_people:false},browser_actor_authority:false}),false);assert.equal(h.operatorContextAllowed({ok:true,operator:{role:"OWNER",can_manage_sponsored_people:true},browser_actor_authority:true}),false)});
test("browser invitation payload cannot forge authority",()=>{const p=h.invitationPayload(input);assert.deepEqual(Object.keys(p),["first_name","last_name","relationship","whatsapp_number","preferred_language","concierge_choice","form_of_address","personal_message","contact_consent_attested","entitlements"]);for(const f of h.FORBIDDEN_AUTHORITY_FIELDS)assert.equal(Object.hasOwn(p,f),false)});
test("Person hinzufügen flow and required consent are present",()=>{assert.match(konto,/id="familyPersonAddButton"[^>]*>Person hinzufügen/);assert.match(konto,/id="familyFirstName"[^>]*required/);assert.match(konto,/id="familyLastName"[^>]*required/);assert.match(konto,/id="familyWhatsappNumber"[^>]*required/);assert.match(konto,/id="familyContactConsent"[^>]*required/);assert.equal(h.invitationPayload({...input,contact_consent_attested:false}),null)});
test("phone validation is UX-only and rejects implausible input",()=>{assert.equal(h.plausiblePhone("+49 170 0000011"),true);assert.equal(h.plausiblePhone("abc"),false);assert.equal(h.plausiblePhone("123"),false)});
test("languages include de tr en fr es and stay BCP47 extensible",()=>{for(const code of ["de","tr","en","fr","es"])assert.match(konto,new RegExp('value="'+code+'"'));assert.equal(h.normalizeLanguage("de-at"),"de-AT");assert.equal(h.normalizeLanguage("pl"),"pl");assert.equal(h.normalizeLanguage("bad language"),null)});
test("concierge selection reuses existing NAHWERK catalog",()=>{assert.match(konto,/Concierge auswählen/);assert.match(konto,/assets\/concierge-carousel\.js\?v=20/);assert.match(js,/NAHWERK_CONCIERGES/);for(const key of ["nilo","mira","lena","leyla","hartmut","zuri","jabari"])assert.match(carousel,new RegExp('\\["'+key+'"'))});
test("sponsored feature codes are exact and all quantities are numeric nonnegative without unlimited",()=>{assert.deepEqual(h.FEATURE_CODES,["whatsapp_dialog","app_dialog","web_research","document_analysis","image_analysis","image_generation","reminders","concierge_execution","phone_concierge","voice_input"]);assert.equal(h.buildEntitlements({...entitlements,voice_input:-1}),null);assert.equal(h.buildEntitlements({...entitlements,voice_input:"x"}),null);assert.doesNotMatch(konto,/unlimited|unbegrenzt/i)});
test("no checkout Stripe or price is added to OWNER slice",()=>{const start=konto.indexOf('id="familyOwnerPanel"'),end=konto.indexOf("</article>",start);const slice=konto.slice(start,end);assert.doesNotMatch(slice,/checkout|stripe|\d+[,.]\d{2}\s*€/i)});
test("runtime inert causes zero family network requests and no fake success",async()=>{let calls=0;const fetchImpl=async()=>{calls++;throw Error("no")};const results=await Promise.all([h.getOperatorContext({base:null,token,fetchImpl}),h.getManagedPeople({base:null,token,fetchImpl}),h.getInvitations({base:null,token,fetchImpl}),h.createInvitation({base:null,token,input,fetchImpl,storage:storage(),cryptoImpl:webcrypto})]);assert.equal(calls,0);for(const r of results){assert.equal(r.networkRequestMade,false);assert.notEqual(r.ok,true)}assert.equal(results[3].message,h.INERT_MESSAGE)});
test("stable idempotency key is reused after uncertain error",async()=>{const s=storage(),keys=[];const first=await h.createInvitation({base:"http://127.0.0.1/mock",token,input,storage:s,cryptoImpl:webcrypto,fetchImpl:async(_u,i)=>{keys.push(i.headers["Idempotency-Key"]);throw Error("uncertain")}});assert.equal(first.ok,false);const second=await h.createInvitation({base:"http://127.0.0.1/mock",token,input,storage:s,cryptoImpl:webcrypto,fetchImpl:async(_u,i)=>{keys.push(i.headers["Idempotency-Key"]);return response(201,{ok:true,state:"MESSAGE_PENDING",duplicate:false,outbound:{provider_execution:false}})}});assert.equal(second.ok,true);assert.equal(keys[0],keys[1])});
test("create request uses exact auth headers and business-only payload",async()=>{let seen;await h.createInvitation({base:"http://127.0.0.1/mock",token,input,storage:storage(),cryptoImpl:webcrypto,fetchImpl:async(u,i)=>{seen={u,i};return response(201,{ok:true,state:"MESSAGE_PENDING",duplicate:false,outbound:{provider_execution:false}})}});assert.match(seen.u,/\/operator\/managed-people\/invitations$/);assert.equal(seen.i.headers.Authorization,"Bearer "+token);assert.equal(seen.i.headers["Content-Type"],"application/json");assert.match(seen.i.headers["Idempotency-Key"],/^[A-Za-z0-9._:-]{16,200}$/);const body=JSON.parse(seen.i.body);assert.deepEqual(Object.keys(body),h.INVITE_FIELDS);for(const f of h.FORBIDDEN_AUTHORITY_FIELDS)assert.equal(Object.hasOwn(body,f),false)});
test("server response cannot fake provider execution success",async()=>{const r=await h.createInvitation({base:"http://127.0.0.1/mock",token,input,storage:storage(),cryptoImpl:webcrypto,fetchImpl:async()=>response(201,{ok:true,state:"MESSAGE_SENT",duplicate:false,outbound:{provider_execution:true}})});assert.equal(r.ok,false);assert.equal(r.kind,"invalid_server_confirmation")});
test("managed people states map safely",()=>{const expected={INVITE_CREATED:"Einladung vorbereitet",MESSAGE_PENDING:"Versand wird vorbereitet",MESSAGE_SENT:"Einladung gesendet",AWAITING_ACCEPTANCE:"Wartet auf Bestätigung",ACCEPTED:"Aktiv",ACTIVE:"Aktiv",DECLINED:"Abgelehnt",EXPIRED:"Abgelaufen",REVOKED:"Widerrufen",SEND_UNCERTAIN:"Versand wird geprüft",SEND_FAILED:"Versand fehlgeschlagen",SUSPENDED:"Pausiert"};for(const [state,label] of Object.entries(expected))assert.equal(h.stateLabel(state),label);assert.equal(h.stateLabel("INTERNAL_SECRET"),"Status wird geprüft")});
test("managed people and invitation lists merge without IDs in labels",()=>{const rows=h.mergeServerPeople({ok:true,people:[{id:"00000000-0000-4000-8000-000000000501",relationship:"MOTHER",status:"ACTIVE",recipient:{id:"00000000-0000-4000-8000-000000000601",first_name:"Ayse",last_name:"Example",preferred_language:"tr",concierge_choice:"leyla"}}]},{ok:true,invitations:[{id:"00000000-0000-4000-8000-000000000601",first_name:"Ayse",last_name:"Example",state:"ACCEPTED"},{id:"00000000-0000-4000-8000-000000000602",first_name:"Ali",last_name:"Example",relationship:"FATHER",preferred_language:"de",concierge_choice:"hartmut",state:"MESSAGE_PENDING"}]});assert.equal(rows.length,2);assert.equal(rows[0].status,"ACTIVE");assert.equal(rows[1].status,"MESSAGE_PENDING")});
test("usage rendering is read-only granted used remaining",()=>{const rows=h.usageRows({ok:true,usage:[{feature_code:"whatsapp_dialog",granted:5,used:2,remaining:3}]});const wa=rows.find(r=>r.feature_code==="whatsapp_dialog");assert.deepEqual(wa,{feature_code:"whatsapp_dialog",label:"WhatsApp-Dialoge",granted:5,used:2,remaining:3})});
test("entitlement update sends exact list and no usage manipulation",async()=>{let seen;const id="00000000-0000-4000-8000-000000000501";await h.updateEntitlements({base:"http://127.0.0.1/mock",token,id,entitlements:input.entitlements,fetchImpl:async(u,i)=>{seen={u,i};return response(200,{ok:true,entitlements:[]})}});assert.match(seen.u,/\/entitlements$/);assert.deepEqual(JSON.parse(seen.i.body),{entitlements:input.entitlements});assert.doesNotMatch(seen.i.body,/used|remaining|usage/)});
test("suspend resume revoke are path-only server transitions and revoke confirmation UI exists",async()=>{const id="00000000-0000-4000-8000-000000000501",calls=[];for(const op of ["suspend","resume","revoke"])await h.transition({base:"http://127.0.0.1/mock",token,id,operation:op,fetchImpl:async(u,i)=>{calls.push({u,i});return response(200,{ok:true,status:op==="suspend"?"SUSPENDED":op==="resume"?"ACTIVE":"REVOKED"})}});assert.deepEqual(calls.map(x=>new URL(x.u).pathname.split("/").pop()),["suspend","resume","revoke"]);for(const c of calls)assert.deepEqual(JSON.parse(c.i.body),{});assert.match(js,/Sponsored Access wirklich beenden/);assert.match(js,/Person und Inhalte werden dadurch nicht gelöscht/)});
test("privacy boundary excludes private content surfaces from OWNER panel",()=>{const start=konto.indexOf('id="familyOwnerPanel"'),end=konto.indexOf("</article>",start),slice=konto.slice(start,end);for(const term of ["WhatsApp-Nachrichten","Conversation","Memory","Tasks","E-Mails","Safety-Inhalte"])assert.doesNotMatch(slice,new RegExp(term,"i"));assert.match(slice,/keine privaten Kommunikationsinhalte/)});
test("mobile desktop CSS and prior email telephone header remain unchanged",()=>{assert.match(css,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/@media\(max-width:680px\)/);assert.match(email,/WEBSITE_EMAIL_INTEGRATION_CONTRACT_V1/);assert.match(phone,/b9cae952e1c9cdae45a238d9cd902a9f2d798452/);assert.match(home,/body\.overview-page\.nw-header-scrolled \.top/)});
