import test from 'node:test';import assert from 'node:assert/strict';
import * as c from '../src/index.js';import {localParts,timezoneSupported} from '../src/timezone.js';
const base=(x={})=>c.reminderDefinition({reminder_id:'r1',person_id:'fixture-person',account_id:'fixture-account',created_by_person_id:'fixture-person',title:'Test',schedule:{at:'2026-09-15T10:00:00Z'},...x});
test('01 one-time reminder',()=>assert.equal(base().reminder_type,'ONE_TIME'));
test('02 daily reminder',()=>assert.ok(c.scheduleOccurrence({daily:true},'2026-08-26T10:00:00Z')>new Date('2026-08-26')));
test('03 weekly reminder',()=>assert.equal(c.scheduleOccurrence({weekly:true},'2026-08-26T10:00:00Z').getUTCDate(),2));
test('04 weekdays modeled',()=>assert.deepEqual(base({schedule:{weekdays:[1,3,5]}}).schedule.weekdays,[1,3,5]));
test('05 end date modeled',()=>assert.equal(base({schedule:{end_at:'2026-12-31'}}).schedule.end_at,'2026-12-31'));
test('06 Europe Berlin',()=>assert.equal(timezoneSupported('Europe/Berlin'),true));
test('07 DST summer to winter',()=>{assert.equal(localParts('2026-10-24T08:00:00Z').hour,'10');assert.equal(localParts('2026-10-26T09:00:00Z').hour,'10')});
test('08 DST winter to summer',()=>{assert.equal(localParts('2026-03-28T09:00:00Z').hour,'10');assert.equal(localParts('2026-03-30T08:00:00Z').hour,'10')});
test('09 due transition',()=>assert.equal(c.transition({...base(),status:c.Status.SCHEDULED},c.Status.DUE).status,'DUE'));
test('10 delivery',async()=>{const p=new c.FixtureReminderDeliveryProvider();await p.send_delivery({},'k');assert.equal(p.sent.length,1)});
test('11 acknowledged',()=>assert.equal(c.acknowledgement('gesehen').successful,true));
test('12 snooze 5',()=>assert.equal(c.snooze('2026-08-26T10:00:00Z','minutes',5).toISOString(),'2026-08-26T10:05:00.000Z'));
test('13 snooze custom',()=>assert.equal(c.snooze(Date.now(),'custom','2026-09-01T12:00:00Z').toISOString(),'2026-09-01T12:00:00.000Z'));
test('14 no duplicate send',async()=>{const p=new c.FixtureReminderDeliveryProvider();await p.send_delivery({},'k');await p.send_delivery({},'k');assert.equal(p.sent.length,1)});
test('15 idempotency',()=>assert.equal(c.deliveryIdempotencyKey('r','2026-01-01'),'r:2026-01-01T00:00:00.000Z'));
test('16 claim lease',()=>assert.equal(new c.LeaseStore().claim('k','w'),true));
test('17 second worker blocked',()=>{const s=new c.LeaseStore();s.claim('k','a',1,100);assert.equal(s.claim('k','b',2,100),false)});
test('18 provider timeout',async()=>{const p=new c.FixtureReminderDeliveryProvider({timeout:true});await assert.rejects(()=>p.send_delivery({},'k'),/timeout/)});
test('19 controlled retry',()=>assert.equal(c.retryDecision({retryable:true},1,3),true));
test('20 invalid no retry',()=>assert.equal(c.retryDecision({retryable:false},1,3),false));
test('21 cancelled no send state',()=>assert.equal(base({status:c.Status.CANCELLED}).status,'CANCELLED'));
test('22 expired no send state',()=>assert.equal(base({status:c.Status.EXPIRED}).status,'EXPIRED'));
test('23 missed normal no safety',()=>assert.equal(c.canEscalateReminder(base({status:c.Status.MISSED})),false));
test('24 checkin',()=>assert.equal(c.checkInDefinition({check_in_id:'c',person_id:'p',prompt:'ok?'}).prompt,'ok?'));
test('25 second checkin delay',()=>assert.equal(c.checkInDefinition({check_in_id:'c',person_id:'p',prompt:'ok?'}).follow_up_delay,900000));
test('26 safety disabled',()=>assert.equal(c.safetyDecision({definition:base()}).escalate,false));
test('27 safety enabled',()=>assert.equal(c.safetyDecision({definition:base({reminder_type:c.ReminderType.SAFETY,escalation_policy:{enabled:true}})}).escalate,true));
test('28 relationship without scope',()=>{const d=base({reminder_type:c.ReminderType.SAFETY,escalation_policy:{enabled:true,escalation_level:c.EscalationLevel.TRUSTED_CONTACT}});assert.equal(c.safetyDecision({definition:d,authorization:{relationship:'daughter',scopes:[]}}).escalate,false)});
test('29 valid safety scope',()=>assert.equal(c.authorizeFamilyAlert({scopes:['safety.receive_alert']}),true));
test('30 minimal family alert',()=>assert.deepEqual(Object.keys(c.familyAlert({person_id:'p',at:'x',level:'l',action:'call'})).sort(),['at','check_in_unanswered','escalation_level','person_id','required_action'].sort()));
test('31 voice not auto executed',()=>{const d=base({reminder_type:c.ReminderType.SAFETY,escalation_policy:{enabled:true,escalation_level:c.EscalationLevel.VOICE_CHECK}});assert.equal(c.safetyDecision({definition:d}).execute_voice,false)});
test('32 emergency default false',()=>assert.equal(c.escalationPolicy().emergency_services_allowed,false));
test('33 human handoff gate',()=>{const d=base({reminder_type:c.ReminderType.SAFETY,escalation_policy:{enabled:true,escalation_level:c.EscalationLevel.HUMAN_HANDOFF}});assert.equal(c.safetyDecision({definition:d}).human_gate,true)});
test('34 quiet hours',()=>assert.equal(c.quietHours('2026-08-26T23:00:00'),true));
test('35 safety quiet policy separate',()=>assert.notEqual(c.escalationPolicy({allowed_channels:['VOICE_CALL']}).allowed_channels.length,0));
test('36 vacation pause',()=>assert.equal(c.activeOverride(c.temporaryContextOverride('vacation',true,'2099-01-01')),true));
test('37 hospital reha temporary',()=>assert.equal(c.temporaryContextOverride('hospital',true,'2099-01-01').scope,'hospital'));
test('38 temporary override',()=>assert.equal(c.temporaryContextOverride('event',1,'2099-01-01').value,1));
test('39 temporary expires',()=>assert.equal(c.activeOverride(c.temporaryContextOverride('bike','inside','2020-01-01')),false));
test('40 memory no escalation auth',()=>{const d=base({reminder_type:c.ReminderType.SAFETY,escalation_policy:{enabled:true,escalation_level:c.EscalationLevel.TRUSTED_CONTACT}});assert.equal(c.safetyDecision({definition:d,memory:{trusted:true}}).escalate,false)});
test('41 document prepare',()=>assert.equal(c.documentReminderPrepare({deadline:'2026-09-15'}).action,'reminder.prepare'));
test('42 no automatic document reminder',()=>assert.equal(c.documentReminderPrepare({deadline:'2026-09-15'}).requires_approval,true));
test('43 approval hook',()=>assert.equal(c.documentReminderPrepare({deadline:'2026-09-15'}).requires_approval,true));
test('44 daily brief',()=>assert.equal(c.dailyBrief({reminders:[1]}).deliver,false));
test('45 task differs reminder',()=>assert.notEqual(c.ReminderType.TASK,undefined));
test('46 audit no secrets',()=>assert.equal('secret' in c.audit('due',{secret:'x',reminder_id:'r'}),false));
test('47 no medical claim',()=>assert.equal(Object.values(c.ReminderType).includes('DIAGNOSIS'),false));
test('48 fixture data only',()=>assert.match(base().person_id,/fixture/));
test('49 no live providers',()=>assert.equal(typeof c.FixtureReminderDeliveryProvider,'function'));
test('50 production unchanged contract',()=>assert.equal(base().preferred_channel,c.Channel.NONE));
test('51 invalid state jump blocked',()=>assert.throws(()=>c.transition(base(),c.Status.DELIVERED),/invalid transition/));
test('52 negative ack not completed',()=>assert.equal(c.acknowledgement('nein').successful,false));
test('53 unknown ack not completed',()=>assert.equal(c.acknowledgement('vielleicht').successful,false));
test('54 retry bounded',()=>assert.equal(c.retryDecision({retryable:true},3,3),false));
test('55 medication is reminder type',()=>assert.equal(c.ReminderType.MEDICATION,'MEDICATION'));
