import test from 'node:test';import assert from 'node:assert/strict';import{IdentityResolutionEngine as E,InMemoryIdentityStore as S,IdempotencyRegistry,normalizePhone,normalizeEmail,normalizeName,profileCompleteness,assessDuplicate}from'./identity-resolution.mjs';
const p={id:'P1',whatsapp_number:'+491701234567',first_name:null,last_name:null,email:null};const a={id:'A1'};const m={id:'M1',customer_account_id:'A1',person_id:'P1',role:'senior'};const eng=(o={})=>new E(new S({people:o.people||[p],accounts:o.accounts||[],memberships:o.memberships||[],channels:o.channels||[]}));
const cases=[
['new WhatsApp number',()=>assert.equal(eng().resolve({phone:'+491711111111',source_channel:'WHATSAPP',server_asserted_phone:true}).decision,'CREATE_PERSON')],
['same number',()=>assert.equal(eng().resolve({phone:'0170 1234567',source_channel:'WHATSAPP',server_asserted_phone:true}).person_id,'P1')],
['first name enrich',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,first_name:'Peter'}).decision,'ENRICH_EXISTING')],
['last name enrich',()=>assert.equal(eng({people:[{...p,first_name:'Peter'}]}).resolve({phone:p.whatsapp_number,phone_verified:true,first_name:'Peter',last_name:'Müller'}).person_id,'P1')],
['name typo no new',()=>assert.equal(eng({people:[{...p,first_name:'Peter'}]}).resolve({phone:p.whatsapp_number,phone_verified:true,first_name:'Pter'}).person_id,'P1')],
['name changed no new',()=>assert.notEqual(eng({people:[{...p,first_name:'Peter'}]}).resolve({phone:p.whatsapp_number,phone_verified:true,first_name:'Petra'}).decision,'CREATE_PERSON')],
['du sie same',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,form_of_address:'DU'}).person_id,'P1')],
['salutation same',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,salutation:'Herr'}).person_id,'P1')],
['website same phone',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,source_channel:'WEBSITE'}).person_id,'P1')],
['person no account',()=>assert.equal(eng().resolve({existing_person_id:'P1',ensure_account:true}).decision,'CREATE_ACCOUNT')],
['existing account',()=>assert.notEqual(eng({accounts:[a],memberships:[m]}).resolve({existing_person_id:'P1',ensure_account:true,role:'senior'}).decision,'CREATE_ACCOUNT')],
['membership missing',()=>assert.equal(eng({accounts:[a],memberships:[{...m,person_id:'P2'}]}).resolve({existing_person_id:'P1',account_id:'A1',ensure_account:true,role:'senior'}).decision,'CREATE_MEMBERSHIP')],
['membership exists',()=>assert.equal(eng({accounts:[a],memberships:[m]}).resolve({existing_person_id:'P1',account_id:'A1',ensure_account:true,role:'senior'}).membership_id,'M1')],
['verified email',()=>assert.equal(eng({people:[{...p,email:'P@EXAMPLE.COM'}]}).resolve({email:'p@example.com',email_verified:true}).person_id,'P1')],
['new email existing id',()=>assert.equal(eng().resolve({existing_person_id:'P1',email:'new@example.com',email_verified:true}).decision,'ENRICH_EXISTING')],
['email concierge same',()=>assert.equal(eng({people:[{...p,email:'p@example.com'}]}).resolve({email:'p@example.com',email_verified:true,source_channel:'EMAIL'}).person_id,'P1')],
['family same senior phone',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,source_channel:'SUPPORT'}).person_id,'P1')],
['relationship no person',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,relationship:'Mutter'}).person_id,'P1')],
['subscription preserved by identity',()=>assert.equal(eng().resolve({existing_person_id:'P1'}).person_id,'P1')],
['usage preserved by identity',()=>assert.equal(eng().resolve({existing_person_id:'P1'}).create_person_required,false)],
['memory preserved by identity',()=>assert.equal(eng().resolve({existing_person_id:'P1'}).person_id,'P1')],
['reminder preserved by identity',()=>assert.equal(eng().resolve({existing_person_id:'P1'}).person_id,'P1')],
['phone change confirmed id',()=>assert.equal(eng().resolve({existing_person_id:'P1',phone:'+491722222222',phone_verified:true}).person_id,'P1')],
['client foreign phone no authority',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:false,server_asserted_phone:false}).decision,'CREATE_PERSON')],
['duplicate whatsapp execution',()=>{const r=new IdempotencyRegistry();let n=0;r.once('wa1',()=>++n);r.once('wa1',()=>++n);assert.equal(n,1)}],
['duplicate website submit',()=>{const r=new IdempotencyRegistry();let n=0;r.once('web1',()=>++n);r.once('web1',()=>++n);assert.equal(n,1)}],
['idempotency result stable',()=>{const r=new IdempotencyRegistry();assert.equal(r.once('x',()=>7),r.once('x',()=>9))}],
['concurrent create semantic key',()=>{const r=new IdempotencyRegistry();let n=0;for(let i=0;i<2;i++)r.once('person:'+normalizePhone('01701111111'),()=>++n);assert.equal(n,1)}],
['two people same phone review',()=>assert.equal(eng({people:[p,{...p,id:'P2'}]}).resolve({phone:p.whatsapp_number,phone_verified:true}).decision,'NEEDS_REVIEW')],
['same names different phones possible',()=>assert.equal(eng({people:[{...p,first_name:'Peter',last_name:'Müller'}]}).resolve({phone:'+491799999999',phone_verified:true,first_name:'Peter',last_name:'Müller'}).decision,'CREATE_PERSON')],
['first name only no match',()=>assert.equal(eng().resolve({first_name:'Peter'}).decision,'CREATE_PERSON')],
['last name only no match',()=>assert.equal(eng().resolve({last_name:'Müller'}).decision,'CREATE_PERSON')],
['fuzzy name no merge',()=>assert.equal(eng().resolve({first_name:'Petr'}).create_person_required,true)],
['verified phone over name',()=>assert.equal(eng({people:[{...p,first_name:'Peter'}]}).resolve({phone:p.whatsapp_number,phone_verified:true,first_name:'Else'}).person_id,'P1')],
['verified email over name',()=>assert.equal(eng({people:[{...p,email:'p@example.com',first_name:'Peter'}]}).resolve({email:'p@example.com',email_verified:true,first_name:'Else'}).person_id,'P1')],
['existing id highest',()=>assert.equal(eng({people:[p,{id:'P2',whatsapp_number:'+491711111111'}]}).resolve({existing_person_id:'P1',phone:'+491711111111',phone_verified:true}).person_id,'P1')],
['wa website neutral',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,source_channel:'WEBSITE'}).person_id,'P1')],
['wa email neutral',()=>assert.equal(eng({people:[{...p,email:'p@example.com'}]}).resolve({email:'p@example.com',email_verified:true,source_channel:'EMAIL'}).person_id,'P1')],
['android whatsapp neutral',()=>assert.equal(eng().resolve({phone:p.whatsapp_number,phone_verified:true,source_channel:'ANDROID'}).person_id,'P1')],
['account not person',()=>assert.equal(eng({accounts:[a],memberships:[m]}).resolve({existing_person_id:'P1',account_id:'A1'}).person_id,'P1')],
['multiple accounts model',()=>{const s=new S({people:[p],accounts:[a,{id:'A2'}],memberships:[m,{id:'M2',customer_account_id:'A2',person_id:'P1',role:'payer'}]});assert.equal(s.memberships.filter(x=>x.person_id==='P1').length,2)}],
['shared phone conflict',()=>assert.equal(eng({people:[p,{...p,id:'P2'}]}).resolve({phone:p.whatsapp_number,phone_verified:true}).review_required,true)],
['profile completeness',()=>assert.equal(profileCompleteness({phone:'+49',first_name:'P',last_name:'M',email:'e',form_of_address:'SIE'}),5)],
['missing last allowed',()=>assert.equal(eng().resolve({phone:'+491711111111',phone_verified:true,first_name:'P'}).decision,'CREATE_PERSON')],
['missing first initial allowed',()=>assert.equal(eng().resolve({phone:'+491711111111',phone_verified:true}).decision,'CREATE_PERSON')],
['no subscription creation enrich',()=>assert.equal(eng().resolve({existing_person_id:'P1',first_name:'P'}).create_account_required,false)],
['no usage creation enrich',()=>assert.equal(eng().resolve({existing_person_id:'P1',first_name:'P'}).create_membership_required,false)],
['no auto merge',()=>assert.equal(eng({people:[p,{...p,id:'P2'}]}).resolve({phone:p.whatsapp_number,phone_verified:true}).confidence,'CONFLICT')],
['audit data sparse',()=>assert.ok(!JSON.stringify(eng().resolve({existing_person_id:'P1'})).includes('token'))],
['no real customer data fixture',()=>assert.deepEqual([p.id,a.id,m.id],['P1','A1','M1'])]
];for(const[c,f]of cases)test(c,f);test('normalizers',()=>{assert.equal(normalizePhone(' (0170) 123-4567 '),'+491701234567');assert.equal(normalizeEmail(' P@EXAMPLE.COM '),'p@example.com');assert.equal(normalizeName(' Peter   Müller '),'Peter Müller');assert.equal(assessDuplicate({phone:p.whatsapp_number,phone_verified:true},{phone:p.whatsapp_number,phone_verified:true}).signal,'verified_phone')});
