const ProviderType=Object.freeze({GMAIL:'GMAIL',MICROSOFT:'MICROSOFT',GMX:'GMX',T_ONLINE:'T_ONLINE',WEB_DE:'WEB_DE',GENERIC_IMAP:'GENERIC_IMAP'});
const AuthMethod=Object.freeze({OAUTH:'OAUTH',APP_PASSWORD:'APP_PASSWORD',EMAIL_PROGRAM_PASSWORD:'EMAIL_PROGRAM_PASSWORD',IMAP_CREDENTIAL:'IMAP_CREDENTIAL',OTHER_SECURE:'OTHER_SECURE'});
const Classification=Object.freeze({IMPORTANT:'IMPORTANT',ACTION_REQUIRED:'ACTION_REQUIRED',INVOICE:'INVOICE',CONTRACT:'CONTRACT',APPOINTMENT:'APPOINTMENT',PERSONAL:'PERSONAL',NEWSLETTER:'NEWSLETTER',ADVERTISEMENT:'ADVERTISEMENT',SPAM_SUSPECTED:'SPAM_SUSPECTED',FRAUD_SUSPECTED:'FRAUD_SUSPECTED',OTHER:'OTHER'});
const Priority=Object.freeze({LOW:'LOW',NORMAL:'NORMAL',HIGH:'HIGH',URGENT:'URGENT'});
class ExecutionNotAllowed extends Error{constructor(action){super(`ExecutionNotAllowed:${action}`);this.code='EXECUTION_NOT_ALLOWED'}}
class ProviderUnavailable extends Error{constructor(){super('ProviderUnavailable');this.code='PROVIDER_UNAVAILABLE'}}
class RateLimited extends Error{constructor(){super('RateLimited');this.code='RATE_LIMITED'}}
const CAPS={
 GMAIL:{supports_oauth:true,supports_imap:false,supports_threads:true,supports_labels:true,supports_folders:false,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false},
 MICROSOFT:{supports_oauth:true,supports_imap:false,supports_threads:false,supports_labels:false,supports_folders:true,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false},
 GMX:{supports_oauth:false,supports_imap:true,supports_threads:false,supports_labels:false,supports_folders:true,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false},
 T_ONLINE:{supports_oauth:false,supports_imap:true,supports_threads:false,supports_labels:false,supports_folders:true,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false},
 WEB_DE:{supports_oauth:false,supports_imap:true,supports_threads:false,supports_labels:false,supports_folders:true,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false},
 GENERIC_IMAP:{supports_oauth:false,supports_imap:true,supports_threads:false,supports_labels:false,supports_folders:true,supports_attachments:true,supports_incremental_sync:true,supports_drafts:false,supports_send:false,supports_move:false,supports_trash:false,supports_spam:false}
};
function emailAccount(x){const forbidden=['password','secret','token','refresh_token','credential'];for(const k of forbidden)if(k in x)throw new Error('credential material forbidden');return Object.freeze({email_account_id:x.email_account_id,person_id:x.person_id,provider_type:x.provider_type,email_address:x.email_address,display_name:x.display_name||'',auth_method:x.auth_method,credential_ref:x.credential_ref||null,connection_status:x.connection_status||'DISCONNECTED',capabilities:{...CAPS[x.provider_type]},folder_mapping:x.folder_mapping||{},sync_mode:x.sync_mode||'INCREMENTAL',last_sync_at:x.last_sync_at||null,created_at:x.created_at||new Date(0).toISOString()})}
function normalizeMessage(account,raw,{includeContent=false,includeAttachments=false}={}){return {message_id:`${account.email_account_id}:${raw.id}`,email_account_id:account.email_account_id,person_id:account.person_id,provider_message_id:raw.id,thread_id:raw.thread_id||null,folder:raw.folder||'INBOX',from:raw.from||'',to:raw.to||[],cc:raw.cc||[],subject:raw.subject||'',sent_at:raw.sent_at||null,received_at:raw.received_at||null,text_body:includeContent?(raw.text_body||null):null,html_present:Boolean(raw.html_present),attachments:includeAttachments?(raw.attachments||[]):(raw.attachments||[]).map(a=>({id:a.id,name:a.name,size:a.size,loaded:false})),links:includeContent?(raw.links||[]):[],read_state:raw.read_state||'UNREAD',importance:raw.importance||'NORMAL',provider_metadata:{provider:account.provider_type,cursor:raw.cursor||null}}}
function classify(m){const s=`${m.subject||''} ${m.text_body||''}`.toLowerCase();if(/passwort|zugangsdaten|neue iban|remote access|konto.*sperr|phishing/.test(s))return {classification:Classification.FRAUD_SUSPECTED,priority:Priority.URGENT};if(/rechnung|invoice|betrag|fällig/.test(s))return {classification:Classification.INVOICE,priority:Priority.HIGH};if(/vertrag|kündigung|tarifänderung/.test(s))return {classification:Classification.CONTRACT,priority:Priority.HIGH};if(/termin|appointment|reservierung/.test(s))return {classification:Classification.APPOINTMENT,priority:Priority.NORMAL};if(/newsletter/.test(s))return {classification:Classification.NEWSLETTER,priority:Priority.LOW};if(/werbung|angebot nur heute/.test(s))return {classification:Classification.ADVERTISEMENT,priority:Priority.LOW};if(/bitte.*antwort|handlung erforderlich|frist/.test(s))return {classification:Classification.ACTION_REQUIRED,priority:Priority.HIGH};if(m.importance==='HIGH'||/wichtig/.test(s))return {classification:Classification.IMPORTANT,priority:Priority.HIGH};if(/liebe|familie|geburtstag/.test(s))return {classification:Classification.PERSONAL,priority:Priority.NORMAL};return {classification:Classification.OTHER,priority:Priority.NORMAL}}
class EmailProviderConnector{async connect(){return {read_only:true}} async disconnect(){return true} async list_folders(){throw new Error('NotImplemented')} async list_messages(){throw new Error('NotImplemented')} async get_message(){throw new Error('NotImplemented')} async get_thread(){throw new Error('NotImplemented')} async get_attachments(){throw new Error('NotImplemented')} mark_read(){throw new ExecutionNotAllowed('mark_read')} move_message(){throw new ExecutionNotAllowed('move_message')} delete_message(){throw new ExecutionNotAllowed('delete_message')} send_message(){throw new ExecutionNotAllowed('send_message')} create_draft(){throw new ExecutionNotAllowed('create_draft')}}
class FixtureEmailConnector extends EmailProviderConnector{constructor(messages=[],opts={}){super();this.messages=messages;this.opts=opts;this.calls=[]} guard(){if(this.opts.unavailable)throw new ProviderUnavailable();if(this.opts.rateLimited)throw new RateLimited()} async list_folders(){this.guard();return ['INBOX','TRASH']} async list_messages({cursor=null}={}){this.guard();this.calls.push(['list_messages',cursor]);return {messages:this.messages.map(({text_body,attachments,links,...h})=>h),cursor:`c${this.messages.length}`}} async get_message(id){this.guard();this.calls.push(['get_message',id]);return this.messages.find(x=>x.id===id)} async get_thread(id){this.guard();return this.messages.filter(x=>x.thread_id===id)} async get_attachments(id){this.guard();this.calls.push(['get_attachments',id]);return (this.messages.find(x=>x.id===id)||{}).attachments||[]}}
class GmailConnector extends EmailProviderConnector{} class MicrosoftGraphConnector extends EmailProviderConnector{} class ImapConnector extends EmailProviderConnector{}
function authorize(account,ctx,scope='email.read'){if(!ctx||ctx.person_id!==account.person_id)throw new Error('PERSON_MISMATCH');if(ctx.actor_person_id&&ctx.actor_person_id!==account.person_id&&!ctx.scopes?.includes(scope))throw new Error('AUTHORIZATION_REQUIRED');return true}
function documentHook(message,documentCore){if(!documentCore)return null;const docs=(message.attachments||[]).filter(a=>/\.pdf$/i.test(a.name||''));return docs.map(a=>documentCore.analyze(a))}
function fraudHook(message,documentFacts,fraudCore){return fraudCore?fraudCore.assess({message,links:message.links||[],documentFacts}):null}
function memoryContext(memory){return {known_provider:memory?.known_provider||null,known_people:memory?.known_people||[],summary_style:memory?.summary_style||null,language:memory?.language||null,known_contract:memory?.known_contract||null,proves_authenticity:false}}
function summarize(message,assessment=classify(message)){return {email_account_id:message.email_account_id,message_id:message.message_id,classification:assessment.classification,priority:assessment.priority,text:assessment.classification===Classification.FRAUD_SUSPECTED?'Diese E-Mail wirkt verdächtig. Bitte öffnen Sie Links zunächst nicht.':`Neue E-Mail: ${message.subject||'(ohne Betreff)'}`,automatic_delivery:false}}
function digest(messages,type='daily_digest'){let xs=messages.map(m=>({m,a:classify(m)}));if(type==='important_only_digest')xs=xs.filter(x=>['HIGH','URGENT'].includes(x.a.priority));if(type==='unread_digest')xs=xs.filter(x=>x.m.read_state!=='READ');if(type==='action_required_digest')xs=xs.filter(x=>x.a.classification===Classification.ACTION_REQUIRED);return {type,count:xs.length,items:xs.map(x=>summarize(x.m,x.a)),automatic_delivery:false}}
function prepareAction(type,payload){return {phase:'PREPARE',type,payload,execute:false,approval_required:true}}
function executeAction(){throw new ExecutionNotAllowed('execute')}
function safeDeletePlan(messageId){return {phase:'PREPARE',type:'move.to_trash',message_id:messageId,permanent_delete:false,empty_trash:false,retention_required:true,approval_required:true}}
function audit(event){const out={...event};for(const k of Object.keys(out))if(/password|secret|token|credential/i.test(k))out[k]='[REDACTED]';return out}
module.exports={ProviderType,AuthMethod,Classification,Priority,CAPS,ExecutionNotAllowed,ProviderUnavailable,RateLimited,emailAccount,normalizeMessage,classify,EmailProviderConnector,FixtureEmailConnector,GmailConnector,MicrosoftGraphConnector,ImapConnector,authorize,documentHook,fraudHook,memoryContext,summarize,digest,prepareAction,executeAction,safeDeletePlan,audit};