export const ExtractionConfidence=Object.freeze({HIGH:'HIGH',MEDIUM:'MEDIUM',LOW:'LOW',UNKNOWN:'UNKNOWN'});
export const ImageQuality=Object.freeze({GOOD:'GOOD',ACCEPTABLE:'ACCEPTABLE',POOR:'POOR',UNUSABLE:'UNUSABLE'});
export const PageCompleteness=Object.freeze({COMPLETE:'COMPLETE',POSSIBLY_CROPPED:'POSSIBLY_CROPPED',MISSING_PAGES:'MISSING_PAGES',INCOMPLETE:'INCOMPLETE',UNKNOWN:'UNKNOWN'});
export const ProcessingSensitivity=Object.freeze({NORMAL:'NORMAL',PRIVATE:'PRIVATE',SENSITIVE:'SENSITIVE',RESTRICTED:'RESTRICTED'});
export class MissingProviderConfiguration extends Error{constructor(provider){super(`MISSING_PROVIDER_CONFIGURATION:${provider}`);this.code='MISSING_PROVIDER_CONFIGURATION';}}
export class ProviderUnavailable extends Error{constructor(provider){super(`PROVIDER_UNAVAILABLE:${provider}`);this.code='PROVIDER_UNAVAILABLE';}}
export class DocumentExtractionCapabilities{constructor(v={}){for(const k of ['supports_image','supports_pdf','supports_multipage','supports_ocr','supports_layout','supports_tables','supports_forms','supports_handwriting','supports_bounding_boxes','supports_field_confidence','supports_page_confidence','supports_rotation','supports_german','supports_eu_region','supports_zero_data_retention_if_configured'])this[k]=v[k]===true;}}
export class DocumentProcessingPolicy{constructor(v={}){Object.assign(this,{allowed_providers:v.allowed_providers??[],region_requirement:v.region_requirement??null,retention_requirement:v.retention_requirement??null,sensitivity:v.sensitivity??ProcessingSensitivity.PRIVATE,max_pages:v.max_pages??200,allow_external_processing:v.allow_external_processing??true,allow_fallback_provider:v.allow_fallback_provider??true});if(this.sensitivity===ProcessingSensitivity.RESTRICTED&&v.allow_external_processing===undefined)this.allow_external_processing=false;}}
export class ExtractedPage{constructor(v={}){Object.assign(this,{page_number:v.page_number??1,text:v.text??'',width:v.width??null,height:v.height??null,blocks:v.blocks??[],confidence:normalizeConfidence(v.confidence),rotation:v.rotation??0,image_quality:v.image_quality??ImageQuality.ACCEPTABLE});}}
export class ExtractedDocument{constructor(v={}){this.provider=v.provider;this.document_id=v.document_id;this.pages=(v.pages??[]).map((p,i)=>p instanceof ExtractedPage?p:new ExtractedPage({page_number:i+1,...p}));this.text=v.text??this.pages.map(p=>p.text).join('\n');this.blocks=v.blocks??this.pages.flatMap(p=>p.blocks);this.tables=v.tables??[];this.detected_language=v.detected_language??null;this.page_count=v.page_count??this.pages.length;this.completeness=v.completeness??PageCompleteness.UNKNOWN;this.rotation=v.rotation??0;this.extraction_confidence=normalizeConfidence(v.extraction_confidence);this.warnings=v.warnings??[];this.provider_metadata=sanitizeMetadata(v.provider_metadata??{});}}
export function normalizeConfidence(v){if(v==null)return ExtractionConfidence.UNKNOWN;if(typeof v==='string'&&Object.values(ExtractionConfidence).includes(v))return v;const n=Number(v);if(!Number.isFinite(n))return ExtractionConfidence.UNKNOWN;if(n>=.9)return ExtractionConfidence.HIGH;if(n>=.7)return ExtractionConfidence.MEDIUM;return ExtractionConfidence.LOW;}
export function assessImageQuality(s={}){if(s.unreadable)return ImageQuality.UNUSABLE;const bad=['blur','low_contrast','crop','glare','missing_page_area'].filter(k=>s[k]).length;if(bad>=3)return ImageQuality.POOR;if(bad)return ImageQuality.ACCEPTABLE;return ImageQuality.GOOD;}
export function detectCompleteness({page_count=1,expected_pages=null,cropped=false,missing_page_area=false}={}){if(expected_pages&&page_count<expected_pages)return PageCompleteness.MISSING_PAGES;if(cropped||missing_page_area)return PageCompleteness.POSSIBLY_CROPPED;return PageCompleteness.COMPLETE;}
export function detectRotation(v){return [0,90,180,270].includes(v)?v:0;}
function sanitizeMetadata(m){const out={};for(const[k,v]of Object.entries(m))if(!/raw|document|image|content|secret|token|key/i.test(k))out[k]=v;return out;}
export function buildExtractionPlan(input,policy=new DocumentProcessingPolicy(),providers=DEFAULT_CAPABILITIES){const pages=input.page_count??1;if(pages>policy.max_pages)throw Object.assign(new Error('MAX_PAGE_LIMIT_EXCEEDED'),{code:'MAX_PAGE_LIMIT_EXCEEDED'});if(!policy.allow_external_processing)return {provider:'fixture',reason:'EXTERNAL_PROCESSING_BLOCKED',estimated_cost:null};const needs={pdf:input.kind==='pdf',image:['image','screenshot'].includes(input.kind),tables:input.document_hint==='invoice'||input.needs_tables===true,multipage:pages>1};const order=needs.tables?['google_document_ai','azure_document_intelligence','aws_textract','openai_vision']:needs.pdf||needs.multipage?['google_document_ai','azure_document_intelligence','aws_textract','openai_vision']:['openai_vision','google_document_ai','azure_document_intelligence','aws_textract'];for(const p of order){if(policy.allowed_providers.length&&!policy.allowed_providers.includes(p))continue;const c=providers[p];if(!c)continue;if(needs.pdf&&!c.supports_pdf||needs.image&&!c.supports_image||needs.tables&&!c.supports_tables||needs.multipage&&!c.supports_multipage)continue;if(policy.region_requirement==='EU'&&!c.supports_eu_region)continue;if(policy.retention_requirement==='ZERO'&&!c.supports_zero_data_retention_if_configured)continue;return {provider:p,reason:'CAPABILITY_MATCH',estimated_cost:estimateCost(p,pages)};}throw Object.assign(new Error('NO_ELIGIBLE_PROVIDER'),{code:'NO_ELIGIBLE_PROVIDER'});}
export function estimateCost(provider,pages){const perPage={google_document_ai:.0015,azure_document_intelligence:null,aws_textract:null,openai_vision:null};return {provider,pages,estimated_usd:perPage[provider]==null?null:Number((perPage[provider]*pages).toFixed(6)),basis:perPage[provider]==null?'RUNTIME_PRICING_REQUIRED':'PUBLIC_OCR_PAGE_PRICE'};}
export class BaseAdapter{constructor(name,{apiKey=null,endpoint=null,transport=null}={}){this.name=name;this.apiKey=apiKey;this.endpoint=endpoint;this.transport=transport;}requireConfigured(){if(!this.apiKey||!this.transport)throw new MissingProviderConfiguration(this.name);}async analyze_document(input){this.requireConfigured();try{return await this.transport({provider:this.name,endpoint:this.endpoint,apiKey:this.apiKey,input});}catch(e){if(e?.status===429)throw Object.assign(new ProviderUnavailable(this.name),{cause:'RATE_LIMIT'});throw new ProviderUnavailable(this.name);}}extract_text(x){return x?.text??''}extract_layout(x){return x?.blocks??[]}extract_pages(x){return x?.pages??[]}extract_tables(x){return x?.tables??[]}detect_rotation(x){return detectRotation(x?.rotation)}detect_completeness(x){return detectCompleteness(x)}}
export class OpenAIDocumentVisionAdapter extends BaseAdapter{constructor(o={}){super('openai_vision',o)}}
export class GoogleDocumentAIAdapter extends BaseAdapter{constructor(o={}){super('google_document_ai',o)}}
export class AzureDocumentIntelligenceAdapter extends BaseAdapter{constructor(o={}){super('azure_document_intelligence',o)}}
export class AwsTextractAdapter extends BaseAdapter{constructor(o={}){super('aws_textract',o)}}
export class FixtureDocumentExtractionProvider{constructor(fixtures={}){this.fixtures=fixtures;this.calls=0;}analyze_document(input){this.calls++;const v=this.fixtures[input.document_id]??input;return new ExtractedDocument({provider:'fixture',...v});}extract_text(f){return f.text??''}extract_layout(f){return f.blocks??f.layout??[]}extract_pages(f){return f.pages??[{text:f.text??''}]}extract_tables(f){return f.tables??[]}detect_rotation(f){return detectRotation(f.rotation)}detect_completeness(f){return detectCompleteness(f)}}
export async function extractWithFallback(input,{primary,fallback=null,policy=new DocumentProcessingPolicy()}={}){try{return await primary.analyze_document(input)}catch(e){if(!fallback||!policy.allow_fallback_provider||policy.sensitivity===ProcessingSensitivity.RESTRICTED)throw e;return fallback.analyze_document(input)}}
export function toDocumentAnalysisRequestFields(extracted){return {extracted_text:extracted.text,extraction_confidence:extracted.extraction_confidence,source_metadata:{provider:extracted.provider,pages:extracted.page_count,completeness:extracted.completeness,rotation:extracted.rotation,layout:extracted.blocks,evidence_pages:extracted.pages.map(p=>({page_number:p.page_number,confidence:p.confidence}))}};}
export function safeExtractionAudit(extracted){return {provider:extracted.provider,document_id:extracted.document_id,page_count:extracted.page_count,confidence:extracted.extraction_confidence,warnings:extracted.warnings};}
export const DEFAULT_CAPABILITIES=Object.freeze({openai_vision:new DocumentExtractionCapabilities({supports_image:true,supports_pdf:true,supports_multipage:true,supports_ocr:true,supports_layout:false,supports_tables:false,supports_forms:false,supports_handwriting:true,supports_bounding_boxes:false,supports_field_confidence:false,supports_page_confidence:false,supports_rotation:true,supports_german:true,supports_eu_region:true,supports_zero_data_retention_if_configured:true}),google_document_ai:new DocumentExtractionCapabilities({supports_image:true,supports_pdf:true,supports_multipage:true,supports_ocr:true,supports_layout:true,supports_tables:true,supports_forms:true,supports_handwriting:true,supports_bounding_boxes:true,supports_field_confidence:true,supports_page_confidence:true,supports_rotation:true,supports_german:true,supports_eu_region:true,supports_zero_data_retention_if_configured:false}),azure_document_intelligence:new DocumentExtractionCapabilities({supports_image:true,supports_pdf:true,supports_multipage:true,supports_ocr:true,supports_layout:true,supports_tables:true,supports_forms:true,supports_handwriting:true,supports_bounding_boxes:true,supports_field_confidence:true,supports_page_confidence:true,supports_rotation:true,supports_german:true,supports_eu_region:true,supports_zero_data_retention_if_configured:false}),aws_textract:new DocumentExtractionCapabilities({supports_image:true,supports_pdf:true,supports_multipage:true,supports_ocr:true,supports_layout:true,supports_tables:true,supports_forms:true,supports_handwriting:true,supports_bounding_boxes:true,supports_field_confidence:true,supports_page_confidence:true,supports_rotation:true,supports_german:true,supports_eu_region:true,supports_zero_data_retention_if_configured:false})});
