export const DocumentType=Object.freeze({LETTER:'LETTER',INVOICE:'INVOICE',REMINDER:'REMINDER',DUNNING_NOTICE:'DUNNING_NOTICE',CONTRACT:'CONTRACT',CONTRACT_CHANGE:'CONTRACT_CHANGE',CANCELLATION:'CANCELLATION',AUTHORITY_LETTER:'AUTHORITY_LETTER',INSURANCE:'INSURANCE',ENERGY:'ENERGY',TELECOM:'TELECOM',BANKING:'BANKING',APPOINTMENT:'APPOINTMENT',OTHER:'OTHER',UNKNOWN:'UNKNOWN'});
export const Confidence=Object.freeze({HIGH:'HIGH',MEDIUM:'MEDIUM',LOW:'LOW',UNKNOWN:'UNKNOWN'});
export const Consistency=Object.freeze({CONSISTENT:'CONSISTENT',CONFLICTING:'CONFLICTING',INCOMPLETE:'INCOMPLETE'});
export const Sensitivity=Object.freeze({NORMAL:'NORMAL',PRIVATE:'PRIVATE',SENSITIVE:'SENSITIVE',RESTRICTED:'RESTRICTED'});
const UNKNOWN=null;
export class DocumentAnalysisRequest{constructor(v){Object.assign(this,{request_id:v.request_id,actor_person_id:v.actor_person_id,subject_person_id:v.subject_person_id,account_id:v.account_id,source_channel:v.source_channel,document_type_hint:v.document_type_hint??DocumentType.UNKNOWN,extracted_text:v.extracted_text??'',extraction_confidence:v.extraction_confidence??Confidence.UNKNOWN,source_metadata:v.source_metadata??{},authorization_context:v.authorization_context??null,created_at:v.created_at??new Date().toISOString()});}}
export class Deadline{constructor(v){Object.assign(this,{type:v.type,date:v.date??UNKNOWN,source_text_reference:v.source_text_reference??UNKNOWN,confidence:v.confidence??Confidence.UNKNOWN,consequence:v.consequence??UNKNOWN,requires_action:!!v.requires_action});}}
export class PaymentDestination{constructor(v={}){Object.assign(this,{iban:v.iban??UNKNOWN,bic:v.bic??UNKNOWN,recipient:v.recipient??UNKNOWN,payment_reference:v.payment_reference??UNKNOWN});}}
export class DocumentRecord{constructor(v={}){Object.assign(this,{document_id:v.document_id,document_type:v.document_type??DocumentType.UNKNOWN,issuer:v.issuer??UNKNOWN,recipient:v.recipient??UNKNOWN,document_date:v.document_date??UNKNOWN,received_date:v.received_date??UNKNOWN,reference_number:v.reference_number??UNKNOWN,contract_reference:v.contract_reference??UNKNOWN,amounts:v.amounts??[],currency:v.currency??'EUR',due_dates:v.due_dates??[],deadlines:v.deadlines??[],payment_destination:v.payment_destination??new PaymentDestination(),contact_information:v.contact_information??[],urls:v.urls??[],obligations:v.obligations??[],requested_actions:v.requested_actions??[],cancellation_information:v.cancellation_information??UNKNOWN,renewal_information:v.renewal_information??UNKNOWN,contract:v.contract??{},confidence:v.confidence??{},warnings:v.warnings??[],consistency:v.consistency??Consistency.CONSISTENT,evidence:v.evidence??{}});}}
export class FixtureDocumentExtractionProvider{extract_text(f){return f.text??''} extract_layout(f){return f.layout??[]} extract_pages(f){return f.pages??[f.text??'']} extract_tables(f){return f.tables??[]}}
const euro=s=>[...s.matchAll(/(\d{1,3}(?:\.\d{3})*,\d{2})\s*€/g)].map(m=>({type:'other',value:Number(m[1].replaceAll('.','').replace(',','.')),source:m[0],confidence:Confidence.HIGH}));
const dates=s=>[...s.matchAll(/(?:bis(?: zum)?\s+)?(\d{1,2}\.\d{1,2}\.\d{4})/gi)].map(m=>new Deadline({type:/bis/i.test(m[0])?'deadline':'date',date:m[1],source_text_reference:m[0],confidence:Confidence.HIGH,requires_action:/bis/i.test(m[0])}));
const iban=s=>s.match(/\bDE\d{20}\b/i)?.[0]?.toUpperCase()??UNKNOWN;
const urls=s=>[...s.matchAll(/https?:\/\/[^\s)]+/g)].map(x=>x[0]);
const ref=s=>s.match(/(?:Kunden|Vertrags|Akten|Rechnungs)(?:nummer|nr\.?)[\s:#-]*([A-Z0-9-]+)/i)?.[1]??UNKNOWN;
function typeOf(s,h){if(h&&h!==DocumentType.UNKNOWN)return h; if(/Mahnung|Zahlungserinnerung/i.test(s))return /Mahnung/i.test(s)?DocumentType.DUNNING_NOTICE:DocumentType.REMINDER;if(/Rechnung/i.test(s))return DocumentType.INVOICE;if(/Vertragsänderung|Preisänderung/i.test(s))return DocumentType.CONTRACT_CHANGE;if(/Kündigung/i.test(s))return DocumentType.CANCELLATION;if(/Vertrag/i.test(s))return DocumentType.CONTRACT;if(/Behörde|Amt|Bescheid/i.test(s))return DocumentType.AUTHORITY_LETTER;if(/Termin/i.test(s))return DocumentType.APPOINTMENT;if(s.trim())return DocumentType.LETTER;return DocumentType.UNKNOWN}
function authorized(r,sensitivity){if(r.actor_person_id===r.subject_person_id)return true;const a=r.authorization_context;return !!(a&&a.document_read===true&&Array.isArray(a.scopes)&&a.scopes.includes('document.analysis')&&(!a.max_sensitivity||[Sensitivity.NORMAL,Sensitivity.PRIVATE,Sensitivity.SENSITIVE,Sensitivity.RESTRICTED].indexOf(sensitivity)<=[Sensitivity.NORMAL,Sensitivity.PRIVATE,Sensitivity.SENSITIVE,Sensitivity.RESTRICTED].indexOf(a.max_sensitivity)));}
export function analyzeDocument(input,{memory={}}={}){const r=input instanceof DocumentAnalysisRequest?input:new DocumentAnalysisRequest(input);const sensitivity=r.source_metadata.sensitivity??Sensitivity.PRIVATE;if(!authorized(r,sensitivity))throw Object.assign(new Error('DOCUMENT_AUTHORIZATION_REQUIRED'),{code:'DOCUMENT_AUTHORIZATION_REQUIRED'});const s=r.extracted_text;const low=[Confidence.LOW,Confidence.UNKNOWN].includes(r.extraction_confidence);const amounts=euro(s);const deadlines=dates(s);const pages=r.source_metadata.pages??1;const expected=r.source_metadata.expected_pages??pages;let consistency=expected>pages?Consistency.INCOMPLETE:Consistency.CONSISTENT;const warnings=[];if(low)warnings.push('LOW_EXTRACTION_CONFIDENCE');if(expected>pages)warnings.push('MISSING_PAGE');const amountValues=[...new Set(amounts.map(a=>a.value))];if(/Gesamt|zu zahlen/i.test(s)&&amountValues.length>1){consistency=Consistency.CONFLICTING;warnings.push('CONFLICTING_AMOUNTS')};const deadlineDates=[...new Set(deadlines.filter(d=>d.requires_action).map(d=>d.date))];if(deadlineDates.length>1){consistency=Consistency.CONFLICTING;warnings.push('CONFLICTING_DEADLINES')};const payment=new PaymentDestination({iban:iban(s),recipient:s.match(/Empfänger[:\s]+([^\n]+)/i)?.[1]?.trim(),payment_reference:s.match(/Verwendungszweck[:\s]+([^\n]+)/i)?.[1]?.trim()});const contract={provider:s.match(/Anbieter[:\s]+([^\n]+)/i)?.[1]?.trim()??UNKNOWN,product:s.match(/Produkt[:\s]+([^\n]+)/i)?.[1]?.trim()??UNKNOWN,start_date:s.match(/Vertragsbeginn[:\s]+(\d{1,2}\.\d{1,2}\.\d{4})/i)?.[1]??UNKNOWN,minimum_term:s.match(/Mindestlaufzeit[:\s]+([^\n]+)/i)?.[1]?.trim()??UNKNOWN,renewal:s.match(/Verlängerung[:\s]+([^\n]+)/i)?.[1]?.trim()??UNKNOWN,cancellation_period:s.match(/Kündigungsfrist[:\s]+([^\n]+)/i)?.[1]?.trim()??UNKNOWN,price:amounts[0]?.value??UNKNOWN,price_change:/Preisänderung/i.test(s),notice_required:/Kündigung.*erforderlich|muss.*kündigen/i.test(s),contract_reference:ref(s)};const record=new DocumentRecord({document_id:r.request_id,document_type:typeOf(s,r.document_type_hint),reference_number:ref(s),contract_reference:contract.contract_reference,amounts,due_dates:deadlines.filter(d=>d.requires_action),deadlines,payment_destination:payment,urls:urls(s),contract,confidence:{extraction:r.extraction_confidence,facts:low?Confidence.LOW:Confidence.HIGH},warnings,consistency,evidence:{amounts:amounts.map(a=>a.source),deadlines:deadlines.map(d=>d.source_text_reference)}});record.memory_context={known_provider:memory.known_provider??UNKNOWN,simple_language:memory.simple_language??false};return record;}
export function simpleExplanation(d){const amount=d.amounts[0];const deadline=d.due_dates[0];return {worum_geht_es:d.document_type===DocumentType.UNKNOWN?'Der Dokumenttyp ist unklar.':`Es handelt sich um: ${d.document_type}.`,muessen_sie_etwas_tun:d.requested_actions.length?'Ja.':'Aus dem Dokument ist keine sichere notwendige Handlung ableitbar.',bis_wann:deadline?.date??'Keine sichere Frist erkannt.',geht_es_um_geld:amount?`Ja, erkannt wurden ${amount.value.toFixed(2).replace('.',',')} €.`:'Kein sicherer Betrag erkannt.',auffaellig:d.warnings.length?d.warnings.join(', '):'Keine strukturelle Auffälligkeit erkannt.'};}
export function fraudHook(d){return {issuer:d.issuer,amount:d.amounts[0]?.value??UNKNOWN,due_date:d.due_dates[0]?.date??UNKNOWN,iban:d.payment_destination.iban,payment_reference:d.payment_destination.payment_reference,urls:d.urls,claimed_contract:d.contract_reference,urgency:d.deadlines.some(x=>x.requires_action)?'DEADLINE_PRESENT':'UNKNOWN',contact_information:d.contact_information};}
export function prepareActions(d){const a=[];if(d.due_dates.length)a.push({action:'reminder.create',state:'PREPARE',execute:false});if([DocumentType.CONTRACT,DocumentType.CONTRACT_CHANGE].includes(d.document_type))a.push({action:'provider_switch.information',state:'INFORMATION',execute:false});if(d.document_type===DocumentType.CANCELLATION)a.push({action:'cancellation.prepare',state:'PREPARE',execute:false});return a;}
export function auditSummary(d){return {document_id:d.document_id,document_type:d.document_type,consistency:d.consistency,warnings:d.warnings};}
