export const ReminderType=Object.freeze({ONE_TIME:'ONE_TIME',RECURRING:'RECURRING',ROUTINE:'ROUTINE',DEADLINE:'DEADLINE',APPOINTMENT:'APPOINTMENT',MEDICATION:'MEDICATION',TASK:'TASK',CHECK_IN:'CHECK_IN',SAFETY:'SAFETY'});
export const Status=Object.freeze({DRAFT:'DRAFT',SCHEDULED:'SCHEDULED',DUE:'DUE',DELIVERING:'DELIVERING',DELIVERED:'DELIVERED',ACKNOWLEDGED:'ACKNOWLEDGED',SNOOZED:'SNOOZED',MISSED:'MISSED',ESCALATING:'ESCALATING',ESCALATED:'ESCALATED',COMPLETED:'COMPLETED',CANCELLED:'CANCELLED',EXPIRED:'EXPIRED',FAILED:'FAILED'});
export const Channel=Object.freeze({WHATSAPP:'WHATSAPP',APP_PUSH:'APP_PUSH',VOICE_CALL:'VOICE_CALL',EMAIL:'EMAIL',NONE:'NONE'});
export const EscalationLevel=Object.freeze({NONE:'NONE',REMIND_AGAIN:'REMIND_AGAIN',CHECK_IN_AGAIN:'CHECK_IN_AGAIN',TRUSTED_CONTACT:'TRUSTED_CONTACT',VOICE_CHECK:'VOICE_CHECK',HUMAN_HANDOFF:'HUMAN_HANDOFF',EMERGENCY_REVIEW:'EMERGENCY_REVIEW'});
const transitions={DRAFT:['SCHEDULED','CANCELLED'],SCHEDULED:['DUE','CANCELLED','EXPIRED'],DUE:['DELIVERING','SNOOZED','MISSED','CANCELLED','EXPIRED'],DELIVERING:['DELIVERED','FAILED','CANCELLED'],DELIVERED:['ACKNOWLEDGED','MISSED','SNOOZED'],ACKNOWLEDGED:['COMPLETED','SNOOZED'],SNOOZED:['SCHEDULED','CANCELLED'],MISSED:['ESCALATING','COMPLETED'],ESCALATING:['ESCALATED','FAILED'],ESCALATED:['COMPLETED'],FAILED:['SCHEDULED','CANCELLED']};
export function transition(r,next){if(!(transitions[r.status]||[]).includes(next))throw new Error(`invalid transition ${r.status}->${next}`);return {...r,status:next,updated_at:new Date().toISOString()};}
export function escalationPolicy(v={}){return {enabled:false,trigger_after:30*60_000,retry_count:1,retry_interval:15*60_000,escalation_level:EscalationLevel.NONE,allowed_channels:[],trusted_contact_scope_required:true,voice_call_allowed:false,human_handoff_allowed:false,emergency_services_allowed:false,...v};}
export function reminderDefinition(v){return {reminder_id:v.reminder_id,person_id:v.person_id,account_id:v.account_id,created_by_person_id:v.created_by_person_id,title:v.title||'',description:v.description||'',reminder_type:v.reminder_type||ReminderType.ONE_TIME,schedule:v.schedule,timezone:v.timezone||'Europe/Berlin',preferred_channel:v.preferred_channel||Channel.NONE,fallback_channels:v.fallback_channels||[],importance:v.importance||'NORMAL',confirmation_required:!!v.confirmation_required,snooze_policy:v.snooze_policy||{},escalation_policy:escalationPolicy(v.escalation_policy),status:v.status||Status.DRAFT,created_at:v.created_at||new Date().toISOString(),updated_at:v.updated_at||new Date().toISOString(),expires_at:v.expires_at||null,metadata:v.metadata||{}};}
export function checkInDefinition(v){return {check_in_id:v.check_in_id,person_id:v.person_id,expected_response_window:v.expected_response_window,prompt:v.prompt,allowed_responses:v.allowed_responses||['ja','nein','später'],follow_up_delay:v.follow_up_delay||15*60_000,escalation_policy:escalationPolicy(v.escalation_policy),status:v.status||Status.SCHEDULED};}
export function acknowledgement(text){const t=String(text).trim().toLowerCase();if(['erledigt','ja','gesehen'].includes(t))return {kind:t==='erledigt'?'COMPLETED':'ACKNOWLEDGED',successful:true};if(['nein'].includes(t))return {kind:'NEGATIVE',successful:false};if(['später','snooze','verschieben'].includes(t))return {kind:'DEFER',successful:false};return {kind:'UNKNOWN',successful:false};}
export function snooze(now,kind,value){const d=new Date(now);const mins={5:5,15:15,30:30,60:60};if(kind==='minutes')d.setMinutes(d.getMinutes()+(mins[value]||Number(value)));else if(kind==='tomorrow')d.setDate(d.getDate()+1);else if(kind==='custom')return new Date(value);else if(kind==='later_today')d.setHours(Math.max(d.getHours()+2,18),0,0,0);return d;}
export function deliveryIdempotencyKey(reminderId,occurrence){return `${reminderId}:${new Date(occurrence).toISOString()}`;}
export class LeaseStore{constructor(){this.m=new Map()}claim(key,worker,now=Date.now(),ttl=60000){const x=this.m.get(key);if(x&&x.lease_until>now&&x.worker_id!==worker)return false;this.m.set(key,{worker_id:worker,lease_until:now+ttl,delivery_attempt:(x?.delivery_attempt||0)+1});return true}release(key,worker){if(this.m.get(key)?.worker_id===worker)this.m.delete(key)}complete(key,worker){const x=this.m.get(key);if(x?.worker_id===worker)this.m.set(key,{...x,complete:true,lease_until:Infinity})}}
export class FixtureReminderDeliveryProvider{constructor({timeout=false,invalid=false}={}){this.sent=[];this.timeout=timeout;this.invalid=invalid}prepare_delivery(r){return {destination:r.person_id,channel:r.preferred_channel}}async send_delivery(p,key){if(this.invalid){const e=new Error('invalid destination');e.retryable=false;throw e}if(this.timeout){const e=new Error('timeout');e.retryable=true;throw e}if(!this.sent.some(x=>x.key===key))this.sent.push({key,p});return {status:'DELIVERED'}}get_delivery_status(){return 'DELIVERED'}cancel_delivery(){return true}}
export function retryDecision(err,attempt,max=3){return !!err?.retryable&&attempt<max;}
export function quietHours(date,{start=22,end=8}={}){const h=new Date(date).getHours();return start>end?h>=start||h<end:h>=start&&h<end;}
export function temporaryContextOverride(scope,value,expires_at){return {scope,value,expires_at};}
export function activeOverride(o,now=new Date()){return !!o&&new Date(o.expires_at)>new Date(now);}
export function authorizeFamilyAlert(ctx){return !!ctx?.scopes?.includes('safety.receive_alert');}
export function familyAlert({person_id,at,level,action}){return {person_id,check_in_unanswered:true,at,escalation_level:level,required_action:action};}
export function safetyDecision({definition,authorization,memory={}}){const p=definition.escalation_policy;if(!p.enabled)return {escalate:false};if(p.escalation_level===EscalationLevel.TRUSTED_CONTACT&&!authorizeFamilyAlert(authorization))return {escalate:false,reason:'scope_required'};if(p.escalation_level===EscalationLevel.VOICE_CHECK)return {escalate:true,execute_voice:false};if(p.escalation_level===EscalationLevel.HUMAN_HANDOFF)return {escalate:p.human_handoff_allowed,human_gate:true};return {escalate:true,emergency_services:false,memory_authorized:false};}
export function documentReminderPrepare(doc){return doc?.deadline?{action:'reminder.prepare',schedule:{at:doc.deadline},requires_approval:true}:null;}
export function dailyBrief({reminders=[],appointments=[],tasks=[],deadlines=[]}){return {reminders,appointments,tasks,deadlines,deliver:false};}
export function audit(event,data={}){const safe={};for(const [k,v] of Object.entries(data))if(!/secret|message|health|diagnos/i.test(k))safe[k]=v;return {event,...safe};}
export function scheduleOccurrence(schedule,from=new Date()){if(schedule.at)return new Date(schedule.at);const d=new Date(from);if(schedule.interval_minutes)d.setMinutes(d.getMinutes()+schedule.interval_minutes);else if(schedule.daily)d.setDate(d.getDate()+1);else if(schedule.weekly)d.setDate(d.getDate()+7);return d;}
export function canEscalateReminder(r){return [ReminderType.CHECK_IN,ReminderType.SAFETY].includes(r.reminder_type)&&r.escalation_policy.enabled;}
